using System;
using System.Collections.Generic;
using Znode.WebStore.Core.ViewModels;
using Znode.Engine.Api.Models;

namespace Znode.Engine.WebStore.ViewModels
{
    public class OrderLineItemViewModel : BaseViewModel
    {
        public OrderLineItemViewModel()
        {
            OrderLineItemCollection = new List<OrderLineItemViewModel>();
        }
        public string AutoAddonSku { get; set; }
        public int OmsOrderLineItemsId { get; set; }
        public int OmsOrderDetailsId { get; set; }
        public int OmsOrderShipmentId { get; set; }
        public string Sku { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal? Weight { get; set; }
        public string DownloadLink { get; set; }
        public decimal? DiscountAmount { get; set; }
        public bool? ShipSeparately { get; set; }
        public DateTime? ShipDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public decimal? ShippingCost { get; set; }
        public string PromoDescription { get; set; }
        public string TransactionNumber { get; set; }
        public int? PaymentStatusId { get; set; }
        public string TrackingNumber { get; set; }
        public bool? IsAutoGeneratedTracking { get; set; }
        public int? OrderLineItemStateId { get; set; }
        public bool? IsRecurringBilling { get; set; }
        public string RecurringBillingPeriod { get; set; }
        public int? RecurringBillingCycles { get; set; }
        public string RecurringBillingFrequency { get; set; }
        public decimal? RecurringBillingAmount { get; set; }
        public string AppliedPromo { get; set; }
        public string CouponsApplied { get; set; }
        public string ExternalId { get; set; }
        public bool IsActive { get; set; }
        public int? ParentOmsOrderLineItemsId { get; set; }
        public int? OrderLineItemRelationshipTypeId { get; set; }
        public List<OrderLineItemViewModel> OrderLineItemCollection { get; set; }
        public string ShippingAddressHtml { get; set; }
        public string DownloadableProductKey { get; set; }
        public decimal SalesTax { get; set; }
        public decimal VAT { get; set; }
        public decimal GST { get; set; }
        public decimal PST { get; set; }
        public decimal HST { get; set; }
        public decimal Total { get; set; }
        public string GroupProductQuantity { get; set; }
        public string GroupProductPrice { get; set; }
        public Dictionary<string, object> PersonaliseValueList { get; set; }
        public List<PersonaliseValueModel> PersonaliseValuesDetail { get; set; }
        public string UOM { get; set; }
        public string OrderLineItemState { get; set; }

        public string GroupId { get; set; }
        public List<OrderAttributeModel> Attributes { get; set; }
        
        public List<OrderWarehouseViewModel> OrderWarehouse { get; set; }
        public Dictionary<string, decimal> AdditionalCost { get; set; }
    }
}