CREATE TYPE [dbo].[SaveForLaterLineitems] AS TABLE(
	[RowId] [int] NULL,
	[OmsTemplateLineItemId] [int] NULL,
	[ParentOmsTemplateLineItemId] [int] NULL,
	[OmsTemplateId] [int] NULL,
	[SKU] [nvarchar](600) NULL,
	[Quantity] [numeric](28, 6) NULL,
	[OrderLineItemRelationshipTypeID] [int] NULL,
	[CustomText] [nvarchar](max) NULL,
	[CartAddOnDetails] [nvarchar](max) NULL,
	[Sequence] [int] NULL,
	[AddOnValueIds] [varchar](max) NULL,
	[BundleProductIds] [varchar](max) NULL,
	[ConfigurableProductIds] [varchar](max) NULL,
	[GroupProductIds] [varchar](max) NULL,
	[PersonalisedAttribute] [xml] NULL,
	[AutoAddon] [varchar](max) NULL,
	[OmsOrderId] [int] NULL,
	[ItemDetails] [nvarchar](max) NULL,
	[Custom1] [nvarchar](max) NULL,
	[Custom2] [nvarchar](max) NULL,
	[Custom3] [nvarchar](max) NULL,
	[Custom4] [nvarchar](max) NULL,
	[Custom5] [nvarchar](max) NULL,
	[GroupId] [nvarchar](max) NULL,
	[ProductName] [nvarchar](1000) NULL,
	[Description] [nvarchar](max) NULL,
	[AddOnQuantity] [nvarchar](max) NULL,
	[CustomUnitPrice] [numeric](28, 6) NULL
)
GO