CREATE TYPE [dbo].[TT_SavecartLineitems] AS TABLE (
    [RowId]                           INT             NULL,
    [OmsSavedCartLineItemId]          INT             NULL,
    [ParentOmsSavedCartLineItemId]    INT             NULL,
    [OmsSavedCartId]                  INT             NULL,
    [SKU]                             NVARCHAR (600)  NULL,
    [Quantity]                        NUMERIC (28, 6) NULL,
    [OrderLineItemRelationshipTypeID] INT             NULL,
    [CustomText]                      NVARCHAR (MAX)  NULL,
    [CartAddOnDetails]                NVARCHAR (MAX)  NULL,
    [Sequence]                        INT             NULL,
    [AddOnValueIds]                   VARCHAR (MAX)   NULL,
    [BundleProductIds]                VARCHAR (MAX)   NULL,
    [ConfigurableProductIds]          VARCHAR (MAX)   NULL,
    [GroupProductIds]                 VARCHAR (MAX)   NULL,
    [PersonalisedAttribute]           XML             NULL,
    [AutoAddon]                       VARCHAR (MAX)   NULL,
    [OmsOrderId]                      INT             NULL,
    [ItemDetails]                     NVARCHAR (MAX)  NULL,
    [Custom1]                         NVARCHAR (MAX)  NULL,
    [Custom2]                         NVARCHAR (MAX)  NULL,
    [Custom3]                         NVARCHAR (MAX)  NULL,
    [Custom4]                         NVARCHAR (MAX)  NULL,
    [Custom5]                         NVARCHAR (MAX)  NULL,
    [GroupId]                         NVARCHAR (MAX)  NULL,
    [ProductName]                     NVARCHAR (1000) NULL,
    [Description]                     NVARCHAR (MAX)  NULL,
    [AddOnQuantity]                   NVARCHAR (MAX)  NULL,
	[CustomUnitPrice]                NUMERIC  (28, 6) NULL
)
