class en {
    QuickOrderLimit: string = "Maximum 50 Products can be added into the Quick List.";
    ErrorEmailAddress: string = "Please use a valid email address.";
    RequiredEmailId: string = "Email ID is required.";
    RequiredNumericValue: string = "Please enter numeric value.";
    RequiredFirstName: string = "First name is required.";
    RequiredLastName: string = "Last name is required.";
    ErrorPhoneNumber: string = "Enter valid phone number.";
    RequiredShippingAddress: string = "Please add shipping address.";
    RequiredBillingAddress: string = "Please add billing address.";
    SelectShippingOption: string = "Please select shipping option.";
    CustomerShippingError: string = "Please enter account number and shipping method.";
    SelectPaymentOption: string = "Please select payment option.";
    SelectCOD: string = "Please select COD for over due amount is less than or equals to zero.";
    ErrorPaymentApplication: string = "Unable to contact payment application. Please reload the page and try again.";
    ErrorPaymentAsNoGatewayAvailable: string = "Could not proceed with payment as no payment gateway is available with this selection.";
    ProcessingPayment: string = "Your payment is processing. Please wait and do not close this window.";
    SelectAtleastOneOrder: string = "At least one order should be selected.";
    SelectAtleastOneRecord: string = "Please select at least one record.";
    ErrorQuantity: string = "Please enter valid quantity.";
    ErrorProcessOrder: string = "Failed to process order.";
    ErrorOrderPlacementCardDataMissing: string = "Error occurred during processing an order. Order could not be placed as card data is missing.";
    ErrorOrderPlacement: string = "Error occurred during processing order. Order could not be placed.";
    SelectCODForZeroOrderTotal: string = "Please select COD for Zero Order Total.";
    ErrorProcessPayment: string = "Unable to process Payment.";
    ErrorProductQuantity: string = "Please specify valid product quantity.";
    RequiredProductQuantity: string = "Please specify the quantity of product(s).";
    SuccessMailSending: string = "Email sent successfully";
    ErrorMailSending: string = "Error in mail sending.";
    ErrorValidSKU: string = "The entered SKU is invalid";
    ErrorValidQuantity: string = "Enter valid quantity.";
    ErrorWholeNumber: string = "Enter whole number.";
    CallForPricing: string = "Call for pricing";
    ErrorSelectedQuantityExceedsMaxCartQuantity: string = "Selected quantity exceeds product maximum given current Shopping Cart quantities.";
    ErrorSelectedQuantityLessThanMinSpecifiedQuantity: string = "Selected quantity is less than minimum specified quantity.";
    ErrorAddToCartFromPDPOrQuickView: string = "This product requires a mandatory personalized message, therefore, can be added to cart only from the product details page.";
    RequiredTemplateName: string = "Please enter template name.";
    EnterQuantityHaving: string = "Please enter quantity having ";
    XNumbersAfterDecimalPoint: string = " numbers after decimal point.";
    SelectedQuantityBetween: string = "Selected quantity should be between ";
    To: string = " to ";
    FullStop: string = ".";
    SelectedCardType: string = "The selected card type is of ";
    SelectCardNumberAndCardType: string = ".  Please check the credit card number and the card type.";
    ErrorProcessCreditCardPayment: string = "We were unable to process your credit card payment. <br /><br />Reason:<br />";
    ContactUsToCompleteOrder: string = "<br /><br />If the problem persists, contact us to complete your order.";
    EnterMinOrderOf: string = "Please enter minimum Order of ";
    EnterMaxOrderOf: string = "Please enter maximum Order of ";
    ErrorPriceNotSet: string = "Price is not set for this product.";
    ErrorRequiredPurchaseOrder: string = "Please enter purchase order number.";
    ErrorFileSizeMessage: string = "File Size is too large. Maximum file size permitted is 5 MB."
    ErrorFileTypeMessage: string = "Please select only JPG,JPEG,PNG,GIF,PDF,DOC,DOCX,PPT,XLS,ZIP,TTF,XLSX,ODT,TXT,CSV file."
    ErrorExtensionNotAllowed: string = "Extension not allowed."
    ErrorFileRequireMessage: string = "Please select file."
    RequiredComment: string = "Comments are required.";
    ZipCodeError: string = "Please enter the Zip Code.";
    ZipCodeMessage: string = "Please wait...";
    NoShippingOptionsFound: string = "No Shipping options found for this zip code. Please try another option.";
    RequiredPhoneNumber: string = "Phone number is required.";
    TextHome: string = "Home";
    ErrorFileRequired: string = "Please select a file."
    ErrorStarRatingRequired: string = "Please provide star rating for the product.";
    ErrorInventoryNotSet: string = "Out of stock";
    TemplateNameAlreadyExist: string = "Template name already exists.";
    CheckingInventory: string = "Checking Inventory...";
    ErrorPurchaseOrderLength: string = "Purchase order number cannot exceed more than 50 characters.";
    LableBrand: string = "Brands";
    AllowedTerritories: string = "Some cart item not allowed to ship in selected country.";
    EnterQuantityError: string = "Please enter the product quantity first";
    SelectCSVFileError: string = "Please select file with .csv extension only";
    FileNotPresentError: string = "File not present.";
    ErrorCSVFileTypeMessage: string = "Please select only CSV file.";
    ErrorBudgetAmount: string = "Budget Amount is required.";
    SelectApprovalUserId: string = "Please select approval name.";
    EmailAddressIsRequired: string = "Email Address is required.";
    SuccessResetPassword: string = "Your password reset link has been sent to your email address.";
    MinQuantityError: string = "We’re sorry, but you must order at least <MinimumOrderQuantity> of this product.";
    MinimumOrderQuantityPlaceholder: string = "<MinimumOrderQuantity>";
    RequiredUserName: string = "Username is required.";
    RequiredPassword: string = "Password is required.";
    RequiredConfirmPassword: string = "Re-type password is required.";
    FirstNameLengthErrorMessage: string = "First Name cannot be longer than 100 characters."
    LastNameLengthErrorMessage: string = "Last Name cannot be longer than 100 characters."
    AddToCartMessage: string = "Added to cart.";
    AddToCartErrorMessage: string = "Add to cart failed.";
    CartUpdateMessage: string = "Cart updated.";
    ConfirmShippingMethod: string = "Please confirm your shipping method";
    QuantityEnteredExceedsQuantityAvailable: string = "Quantity entered exceeds quantity available.";
    WhileSuppliesLast: string = "While supplies last.";
    PendingApproval: string = "PENDING APPROVAL";
    RequiredRecipientName: string = "Recipient name is required.";
    PerOrderLimitFailed: string = "You have exceeded the per order limit. Please delete some of the items from cart or manage the quantity and try again. Your per order limit is  ";
    AnnualOrderLimitFailed: string = "You have exceeded the annual order limit. Please delete some of the items from cart or manage the quantity and try again. Your annual limit is ";
    AddedToCartSucessMessage: string = "Added to cart<a href='/cart'>Click here</a> to view your shopping cart and checkout."
    AddedToCartErrorMessage: string = "Failed to add the product."
    ErrorProductRemoveFromWishList: string = "Product could not be removed from wishlist";
    ErrorCodeE00027: string = "Valid address and zipcode must be entered.";
    BarcodeInvalidMessage: string = "Product not found";
    BarcodeLoadErrorMessage: string = "Unable to load scanner";
    ObsoleteProductErrorMessage: string = "The product is marked as obsolete, please try our other range of products.";
    ErrorRequiredCoupon: string = "Please enter valid Promo Code.";
    InvalidAddressSelection: string = "Please select the correct address.";
    ErrorRequiredVoucher: string = "Please enter valid Voucher.";
    MessageNoProductsInWishlist: string = "There are no products in your wishlist.";
    NumericZipCodeError: string = "Please enter numeric Zip Code.";
    ErrorQtyRequired: string = "Please enter a quantity greater than 0."
    ErrorInvalidReturnShippedQuantity: string = "Please enter an input quantity greater than or equal to 0 and less than or equal to the Shipped Qty.";
    MessageChangesSavedSuccessfully: string = "Changes saved successfully.";
    ErrorSaveOrderTemplate: string = "Please save the order template to proceed";
    ErrorAtLeastOneProductTemplate: string = "Please add products to the template";
    ErrorVoucherAlreadyApplied: string = "Voucher is already applied.";
    ErrorNoVoucherApplied: string = "No further vouchers can be applied.";
    ErrorInValidSKU: string = "The entered SKU is invalid.";
    ErrorOutOfStockMessage: string = "The product is out of stock.";
    ErrorDuplicatedSKU: string = "The product already exists.";
    ErrorMaxCartQuantity: string = "Quantity is more than max order quantity";
    ErrorMinCartQuantity: string = "Quantity is less than min order quantity";
    ErrorDuplicateSKUWithMaxCartQuantity: string = "The product already exists - please adjust the quantities in Quick List";
    ErrorItemNumberField: string = "Product is not present to add in quick list";
    ZeroValueInDecimal: string = "0.00";     
    ErrorCardDetails: string = "Please Enter Card Details.";
    DontTrackInventory: string = "donttrackinventory";
    AllowBackOrdering: string = "allowbackordering";
    AccessDeniedMessage: string = "The page cannot be displayed. Make sure you are authorized to view this page.";
    isObsolete: string = "The product is marked as obsolete, please try our other range of products."
    SuccessSubmitStockNotice: string = "You have successfully subscribed for receiving in-stock notification.";
    ErrorSubmitStockNotice: string = "Error encountered during In-stock Email subscription, enter the details again to subscribe successfully.";
    ErrorAmountDueMessage: string = "The Payment Amount cannot be greater than the Amount Due"
    ErrorpaymentAmountMessage: string = "The Payment Amount cannot be 0."
    InvalidCSVFileType: string = "Please upload a CSV or XLSX file";
    SuccessSavedCart: string = " Cart Saved Successfully."
    DuplicateCart: string = "Name already in use, enter another Cart Name."
    NoCart: string = "Cart Name is required."
    alphanumeric: string = "Only alphanumeric characters are allowed."
    SavedCartNameExist: string = "Name already in use, enter another Cart Name."
    ErrorAtLeastOneSaveCart: string = "Please add products to the Save Cart";
    ErrorSavedcartName: string = "Input value must not exceed the maximum character limit of 100."
    ErrorSelectcartName: string = "Please select saved cart"
    PaypalProcessingPayment: string = "Please wait and do not close this window.";
}