//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Engine.Recommendations.DataModel
{
    using System;
    using System.Collections.Generic;
    using Znode.Libraries.Data;
    
    public partial class ZnodeRecommendedProduct : ZnodeEntityBaseModel
    {
        public long RecommendedProductsID { get; set; }
        public long RecommendationBaseProductsId { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int Occurrence { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeRecommendationBaseProduct ZnodeRecommendationBaseProduct { get; set; }
    }
}
