
  Create View [dbo].[View_Table_FK_Details] as
SELECT C.TABLE_NAME , C.CONSTRAINT_NAME ,KCU.COLUMN_NAME ,  RC.UPDATE_RULE, RC.DELETE_RULE, C2.TABLE_NAME [REF_TABLE_NAME], KCU2.COLUMN_NAME [REF_COLUMN_NAME],
      C2.CONSTRAINT_NAME [REF_CONSTRAINT_NAME]
FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS C 
      INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU 
        ON C.CONSTRAINT_SCHEMA = KCU.CONSTRAINT_SCHEMA 
           AND C.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME 
      inner JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC 
        ON C.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
           AND C.CONSTRAINT_NAME = RC.CONSTRAINT_NAME 
      inner JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS C2 
        ON RC.UNIQUE_CONSTRAINT_SCHEMA = C2.CONSTRAINT_SCHEMA
           AND RC.UNIQUE_CONSTRAINT_NAME = C2.CONSTRAINT_NAME 
      inner JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU2
        ON C2.CONSTRAINT_SCHEMA = KCU2.CONSTRAINT_SCHEMA 
           AND C2.CONSTRAINT_NAME = KCU2.CONSTRAINT_NAME
           AND KCU.ORDINAL_POSITION = KCU2.ORDINAL_POSITION