CREATE VIEW [dbo].[View_GetMediaFolderDetails]
AS
     SELECT ISNULL(NULL, 0) AS MediaCategoryId,
            CAST(0 AS INT) AS MediaId,
            CAST(0 AS INT) AS MediaPathId,
            CAST(0 AS INT) AS MediaAttributeFamilyId,
            CAST(0 AS INT) AS MediaAttributeId,
            CAST(0 AS INT) AS AttributeTypeId,
            CAST('0' AS VARCHAR(300)) AS AttributeTypeName,
            CAST('0' AS VARCHAR(300)) AS MediaAttributeCode,
            CAST(0 AS BIT) AS IsRequired,
            CAST(0 AS BIT) AS IsLocalizable,
            CAST(0 AS BIT) AS IsFilterable,
            CAST('0' AS NVARCHAR(600)) AS MediaAttributeName,
            CAST('0' AS VARCHAR(300)) AS MediaAttributeValue,
            CAST(0 AS INT) AS MediaAttributeValueId,
            CAST(0 AS INT) AS MediaAttributeDefaultValueId,
            CAST('0' AS VARCHAR(600)) AS DefaultAttributeValue,
            CAST('0' AS VARCHAR(8000)) AS MediaPath,
            CAST(0 AS INT) AS RowId,
            CAST(0 AS BIT) AS IsEditable,
            CAST('0' AS VARCHAR(300)) AS ControlName,
            CAST('0' AS VARCHAR(100)) AS ValidationName,
            CAST('0' AS VARCHAR(300)) AS SubValidationName,
            CAST('0' AS VARCHAR(300)) AS RegExp,
            CAST('0' AS VARCHAR(300)) AS ValidationValue,
            CAST(0 AS BIT) AS IsRegExp,
            CAST(0 AS INT) AS CreatedBy;
GO
