//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Multifront.PaymentApplication.Data
{
    using System;
    using System.Collections.Generic;
     using Znode.Multifront.PaymentApplication.Models;
    public partial class ZnodePaymentMethod : ZnodePaymentEntityBaseModel
    {
        public System.Guid PaymentGUID { get; set; }
        public string Token { get; set; }
        public string CreditCardLastFourDigit { get; set; }
        public Nullable<int> CreditCardExpMonth { get; set; }
        public Nullable<int> CreditCardExpYear { get; set; }
        public Nullable<System.Guid> CreditCardAddressId { get; set; }
        public Nullable<int> PaymentSettingID { get; set; }
        public Nullable<System.Guid> CustomersGUID { get; set; }
        public string CustomerProfileId { get; set; }
        public string CreditCardImageUrl { get; set; }
        public bool IsSaveCreditCard { get; set; }
        public string CardType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ZnodePaymentAddress ZnodePaymentAddress { get; set; }
        public virtual ZnodePaymentCustomer ZnodePaymentCustomer { get; set; }
        public virtual ZNodePaymentSetting ZNodePaymentSetting { get; set; }
    }
}
