//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Multifront.PaymentApplication.Data
{
    using System;
    using System.Collections.Generic;
     using Znode.Multifront.PaymentApplication.Models;
    public partial class ZNodeActivityLog : ZnodePaymentEntityBaseModel
    {
        public int ActivityLogId { get; set; }
        public Nullable<int> PaymentSettingId { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string URL { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Data3 { get; set; }
        public string Status { get; set; }
        public string LongData { get; set; }
        public string Source { get; set; }
        public string Target { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
