//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Multifront.PaymentApplication.Data
{
    using System;
    using System.Collections.Generic;
     using Znode.Multifront.PaymentApplication.Models;
    public partial class ZNodePaymentSettingCredential : ZnodePaymentEntityBaseModel
    {
        public int PaymentSettingCredentialId { get; set; }
        public string Partner { get; set; }
        public string Vendor { get; set; }
        public bool TestMode { get; set; }
        public Nullable<int> PaymentSettingId { get; set; }
        public string GatewayUsername { get; set; }
        public string GatewayPassword { get; set; }
        public string TransactionKey { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
    
        public virtual ZNodePaymentSetting ZNodePaymentSetting { get; set; }
    }
}
