//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Multifront.PaymentApplication.Data
{
    using System;
    using System.Collections.Generic;
     using Znode.Multifront.PaymentApplication.Models;
    public partial class ZnodeAuthToken : ZnodePaymentEntityBaseModel
    {
        public int AuthTokenId { get; set; }
        public string AuthToken { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> TotalAttempt { get; set; }
    }
}
