//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Multifront.PaymentApplication.Data
{
    using System;
    using System.Collections.Generic;
     using Znode.Multifront.PaymentApplication.Models;
    public partial class ZNodePaymentGateway : ZnodePaymentEntityBaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZNodePaymentGateway()
        {
            this.ZNodePaymentSettings = new HashSet<ZNodePaymentSetting>();
        }
    
        public int PaymentGatewayId { get; set; }
        public string GatewayName { get; set; }
        public string WebsiteURL { get; set; }
        public string ClassName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string GatewayCode { get; set; }
        public bool IsACHEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZNodePaymentSetting> ZNodePaymentSettings { get; set; }
    }
}
