CREATE TABLE [dbo].[ZnodePublishProductEntityLog] (
    [PublishProductEntityId]        INT            NOT NULL,
    [VersionId]                     INT            NOT NULL,
    [IndexId]                       NVARCHAR (300) NOT NULL,
    [ZnodeProductId]                INT            NOT NULL,
    [ZnodeCatalogId]                INT            NOT NULL,
    [SKU]                           NVARCHAR (300) NOT NULL,
    [LocaleId]                      INT            NOT NULL,
    [Name]                          NVARCHAR (600) NOT NULL,
    [ZnodeCategoryIds]              INT            NOT NULL,
    [IsActive]                      BIT            NOT NULL,
    [Attributes]                    NVARCHAR (MAX) NOT NULL,
    [Brands]                        NVARCHAR (MAX) NOT NULL,
    [CategoryName]                  VARCHAR (300)  NOT NULL,
    [CatalogName]                   VARCHAR (300)  NOT NULL,
    [DisplayOrder]                  INT            NOT NULL,
    [RevisionType]                  VARCHAR (50)   NOT NULL,
    [AssociatedProductDisplayOrder] INT            NOT NULL,
    [ProductIndex]                  INT            NOT NULL,
    [SalesPrice]                    VARCHAR (50)   NULL,
    [RetailPrice]                   VARCHAR (50)   NULL,
    [CultureCode]                   VARCHAR (50)   NULL,
    [CurrencySuffix]                VARCHAR (50)   NULL,
    [CurrencyCode]                  VARCHAR (50)   NULL,
    [SeoDescription]                VARCHAR (1000) NULL,
    [SeoKeywords]                   VARCHAR (1000) NULL,
    [SeoTitle]                      VARCHAR (1000) NULL,
    [SeoUrl]                        VARCHAR (1000) NULL,
    [ImageSmallPath]                VARCHAR (500)  NOT NULL,
    [SKULower]                      NVARCHAR (300) NULL,
    [ElasticSearchEvent]            INT            NULL,
    [ZnodeParentCategoryIds]        VARCHAR (1000) NULL,
    [ModifiedDate]                  DATETIME       NULL,
    [IsSingleProductPublish]        BIT            NULL,
    [IsCacheClear]                  BIT            NULL
);

