CREATE TABLE [dbo].[ZnodeRmaReturnDetails] (
    [RmaReturnDetailsId]          INT             IDENTITY (1, 1) NOT NULL,
    [OmsOrderId]                  INT             NOT NULL,
    [OmsOrderDetailsId]           INT             NOT NULL,
    [OrderNumber]                 NVARCHAR (100)  NOT NULL,
    [ReturnNumber]                NVARCHAR (100)  NOT NULL,
    [ReturnDate]                  DATETIME        NULL,
    [RmaReturnStateId]            INT             NOT NULL,
    [TotalExpectedReturnQuantity] NUMERIC (28, 6) NOT NULL,
    [EmailId]                     VARCHAR (50)    NULL,
    [PortalId]                    INT             NOT NULL,
    [UserId]                      INT             NOT NULL,
    [FirstName]                   NVARCHAR (100)  NULL,
    [LastName]                    NVARCHAR (100)  NULL,
    [AddressId]                   INT             NULL,
    [ShippingId]                  INT             NULL,
    [ShippingNumber]              NVARCHAR (MAX)  NULL,
    [IsTaxCostEdited]             BIT             NULL,
    [SubTotal]                    NUMERIC (28, 6) NULL,
    [ReturnShippingCost]          NUMERIC (28, 6) NULL,
    [DiscountAmount]              NUMERIC (28, 6) NULL,
    [ReturnTaxCost]               NUMERIC (28, 6) NULL,
    [TotalReturnAmount]           NUMERIC (28, 6) NULL,
    [IsActive]                    BIT             NOT NULL,
    [CurrencyCode]                VARCHAR (20)    NULL,
    [CultureCode]                 VARCHAR (100)   NOT NULL,
    [Custom1]                     VARCHAR (MAX)   NULL,
    [Custom2]                     VARCHAR (MAX)   NULL,
    [Custom3]                     VARCHAR (MAX)   NULL,
    [Custom4]                     VARCHAR (MAX)   NULL,
    [Custom5]                     VARCHAR (MAX)   NULL,
    [CreatedBy]                   INT             NOT NULL,
    [CreatedDate]                 DATETIME        NOT NULL,
    [ModifiedBy]                  INT             NOT NULL,
    [ModifiedDate]                DATETIME        NOT NULL,
	[OverDueAmount]	              NUMERIC(28, 6) NULL,
	[IsRefundProcess]	          BIT  CONSTRAINT [DF_ZnodeRmaReturnDetails_ DEFAULT_IsRefundProcess] DEFAULT ((0)) NOT NULL,
	[CSRDiscount] numeric(28, 6) NULL,
	[ReturnShippingDiscount] numeric(28, 6) NULL,
	[ReturnCharges] numeric(28, 6) NULL,
	[VoucherAmount] numeric(28, 6) NULL,
    [ImportDuty] NUMERIC(28,6) NULL,
    CONSTRAINT [PK_ZnodeRmaReturnDetails] PRIMARY KEY CLUSTERED ([RmaReturnDetailsId] ASC),
    CONSTRAINT [FK_ZnodeRmaReturnDetails_ZnodeOmsOrder] FOREIGN KEY ([OmsOrderId]) REFERENCES [dbo].[ZnodeOmsOrder] ([OmsOrderId]),
    CONSTRAINT [FK_ZnodeRmaReturnDetails_ZnodeOmsOrderDetails] FOREIGN KEY ([OmsOrderDetailsId]) REFERENCES [dbo].[ZnodeOmsOrderDetails] ([OmsOrderDetailsId]),
    CONSTRAINT [FK_ZnodeRmaReturnDetails_ZnodePortal] FOREIGN KEY ([PortalId]) REFERENCES [dbo].[ZnodePortal] ([PortalId]),
    CONSTRAINT [FK_ZnodeRmaReturnDetails_ZnodeRmaReturnState] FOREIGN KEY ([RmaReturnStateId]) REFERENCES [dbo].[ZnodeRmaReturnState] ([RmaReturnStateId]),
    CONSTRAINT [FK_ZnodeRmaReturnDetails_ZnodeUser] FOREIGN KEY ([UserId]) REFERENCES [dbo].[ZnodeUser] ([UserId])
);

