--ZPD-20156 Dt-24-June-2022
/*
--SET IDENTITY_INSERT [dbo].[ZnodeShipping] ON
--INSERT INTO [dbo].[ZnodeShipping] ([ShippingId], [ShippingTypeId], [CurrencyId], [ShippingCode], [ShippingName], [HandlingCharge], [HandlingChargeBasedOn], [DestinationCountryCode], [StateCode], [CountyFIPS], [TrackingUrl], [Description], [IsActive], [DisplayOrder], [ZipCode], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DeliveryTimeframe], [CultureId]) VALUES (2, 1, NULL, N'FEDEX_2_DAY', N'FEDEX_2_DAY', 2.000000, N'Amount', N'US', NULL, NULL, NULL, N'FedEx 2 Day&reg;', 1, 2, NULL, 2, '20170210 07:19:25.000', 2, '20170210 07:21:46.000', NULL, NULL)
--INSERT INTO [dbo].[ZnodeShipping] ([ShippingId], [ShippingTypeId], [CurrencyId], [ShippingCode], [ShippingName], [HandlingCharge], [HandlingChargeBasedOn], [DestinationCountryCode], [StateCode], [CountyFIPS], [TrackingUrl], [Description], [IsActive], [DisplayOrder], [ZipCode], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DeliveryTimeframe], [CultureId]) VALUES (4, 3, NULL, N'PRIORITY', N'USPS', 20.000000, N'SubTotal', N'US', NULL, NULL, NULL, N'USPS', 1, 4, NULL, 2, '20170210 07:21:12.000', 2, '20170210 07:21:54.000', NULL, NULL)
--SET IDENTITY_INSERT [dbo].[ZnodeShipping] OFF
--SET IDENTITY_INSERT [dbo].[ZnodeTaxPortal] ON
--INSERT INTO [dbo].[ZnodeTaxPortal] ([TaxPortalId], [PortalId], [AvataxUrl], [AvalaraAccount], [AvalaraLicense], [AvalaraCompanyCode], [AvalaraFreightIdentifier], [STOCCHUrl], [EntityId], [DivisionId], [FreightTaxGroupCode], [FreightTaxItemCode], [CreatedDate], [ModifiedDate], [CreatedBy], [ModifiedBy], [TaxRuleTypeId], [Custom1], [Custom2], [Custom3], [Custom4], [Custom5]) VALUES (1, 7, N'https://development.avalara.net/', N'1100095552', N'6FF15411B5E9D5EF', N'ZN0022', N'PA020659', NULL, NULL, NULL, NULL, NULL, '20190531 15:06:56.200', '20190531 15:06:56.200', 2, 2, NULL, NULL, NULL, NULL, NULL, NULL)
--SET IDENTITY_INSERT [dbo].[ZnodeTaxPortal] OFF
--SET IDENTITY_INSERT [dbo].[ZnodeProfileShipping] ON
--INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (1, 2, 4, 2, '20190603 06:25:57.253', 2, '20190603 06:25:57.253', NULL, NULL)
--INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (2, 2, 2, 2, '20190603 06:25:57.253', 2, '20190603 06:25:57.253', NULL, NULL)
--INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (7, 1, 2, 2, '20190603 06:27:03.163', 2, '20190603 06:27:03.163', NULL, NULL)
--INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (8, 1, 4, 2, '20190603 06:27:03.163', 2, '20190603 06:27:03.163', NULL, NULL)
--SET IDENTITY_INSERT [dbo].[ZnodeProfileShipping] OFF
--SET IDENTITY_INSERT [dbo].[ZnodePortalSmtpSetting] ON
--INSERT INTO [dbo].[ZnodePortalSmtpSetting] ([PortalSmtpSettingId], [PortalId], [ServerName], [UserName], [Password], [Port], [IsEnableSsl], [FromDisplayName], [FromEmailAddress], [BccEmailAddress], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisableAllEmails]) VALUES (5, 7, N'smtp.sendgrid.net', N'th5zP6HMPQaoVz0IHQvKxQ==', N'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', 587, 0, NULL, NULL, NULL, 2, '20190424 00:29:06.467', 2, '20191001 16:01:05.637', 0)
--SET IDENTITY_INSERT [dbo].[ZnodePortalSmtpSetting] OFF
--SET IDENTITY_INSERT [dbo].[ZnodePortalShipping] ON
--INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (18, 7, 2, 2, '20190425 00:37:07.800', 2, '20190425 00:37:07.800', 3)
--INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (20, 7, 4, 2, '20190425 00:37:07.800', 2, '20190425 00:37:07.800', 3)
--SET IDENTITY_INSERT [dbo].[ZnodePortalShipping] OFF
--SET IDENTITY_INSERT [dbo].[ZnodeShippingPortal] ON
--INSERT INTO [dbo].[ZnodeShippingPortal] ([ShippingPortalId], [PortalId], [ShippingOriginAddress1], [ShippingOriginAddress2], [ShippingOriginCity], [ShippingOriginStateCode], [ShippingOriginZipCode], [ShippingOriginCountryCode], [ShippingOriginPhone], [FedExAccountNumber], [FedExLTLAccountNumber], [FedExMeterNumber], [FedExProductionKey], [FedExSecurityCode], [FedExDropoffType], [FedExPackagingType], [FedExUseDiscountRate], [FedExAddInsurance], [UPSUserName], [UPSPassword], [UPSKey], [LTLUPSAccessLicenseNumber], [LTLUPSUsername], [LTLUPSPassword], [LTLUPSAccountNumber], [UPSDropoffType], [UPSPackagingType], [IsUseWarehouseAddress], [USPSShippingAPIURL], [USPSWebToolsUserID], [PackageWeightLimit], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (4, 7, N'1225 Discovery Parkway', N'Suite 155', N'Milwaukee', N'WI', N'53226', N'US', N'+1-855-927-8434', N'8UHG9VP6OrV2qSp688jJhg==', NULL, N'IKOpkTC+qbQn04Mbl/BZ5Q==', N'wOWfd2sWGxYzHAWUDRBx0XeB1YEA+2pJ', N'q8oM2zKjE36pNqNC6mYy7sYaZfYh9vNqja4zn+gIkR8=', N'BUSINESS_SERVICE_CENTER', N'YOUR_PACKAGING', 1, 1, N'l8PcAXBZbWxARbbxtIQwvQ==', N'A3SRKCOHX6pyizEU8k4bWZnXggUHDVa+', N'MDA/u+KFtCOLLUNrXRb685v+Ug8hRdQi', NULL, NULL, NULL, NULL, N'Regular Daily Pickup', N'01', 1, N'http://Production.ShippingAPIs.com/ShippingAPI.dll', N'834ENCOR4758', 65.000000, 2, '20190425 00:34:36.657', 2, '20190603 06:31:07.890', 3)
--SET IDENTITY_INSERT [dbo].[ZnodeShippingPortal] OFF
*/
IF NOT EXISTS (SELECT TOP 1 1 FROM ZnodeShipping WHERE ShippingCode IN ('FEDEX_2_DAY','PRIORITY','65'))
BEGIN
	IF EXISTS (SELECT TOP 1 1 FROM ZnodeManageConditionalDefaultData WHERE ConditionalCode = 'InsertDataForTablesAsPerZPD20156OnlyForInternalPurposeDuringFreshDbCreation' AND IsActive=1)
	BEGIN
		SET IDENTITY_INSERT [dbo].[ZnodeShipping] ON
		INSERT INTO [dbo].[ZnodeShipping] ([ShippingId], [ShippingTypeId], [CurrencyId], [ShippingCode], [ShippingName], [HandlingCharge], [HandlingChargeBasedOn], [DestinationCountryCode], [StateCode], [CountyFIPS], [TrackingUrl], [Description], [IsActive], [DisplayOrder], [ZipCode], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DeliveryTimeframe], [CultureId]) VALUES (2, 1, NULL, N'FEDEX_2_DAY', N'FEDEX_2_DAY', 2.000000, N'Amount', N'US', NULL, NULL, NULL, N'FedEx 2 Day&reg;', 1, 2, NULL, 2, '20170210 07:19:25.000', 2, '20170210 07:21:46.000', NULL, NULL)
		INSERT INTO [dbo].[ZnodeShipping] ([ShippingId], [ShippingTypeId], [CurrencyId], [ShippingCode], [ShippingName], [HandlingCharge], [HandlingChargeBasedOn], [DestinationCountryCode], [StateCode], [CountyFIPS], [TrackingUrl], [Description], [IsActive], [DisplayOrder], [ZipCode], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DeliveryTimeframe], [CultureId]) VALUES (4, 3, NULL, N'PRIORITY', N'USPS', 20.000000, N'SubTotal', N'US', NULL, NULL, NULL, N'USPS', 1, 4, NULL, 2, '20170210 07:21:12.000', 2, '20170210 07:21:54.000', NULL, NULL)
		INSERT INTO [dbo].[ZnodeShipping] ([ShippingId], [ShippingTypeId], [CurrencyId], [ShippingCode], [ShippingName], [HandlingCharge], [HandlingChargeBasedOn], [DestinationCountryCode], [StateCode], [CountyFIPS], [TrackingUrl], [Description], [IsActive], [DisplayOrder], [ZipCode], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DeliveryTimeframe], [CultureId]) VALUES (6, 2, 199, N'65', N'UPS', CAST(10.000000 AS Numeric(28, 6)), N'Amount', N'US', NULL, NULL, NULL, N'UPS', 1, 99, NULL, 3, CAST(N'2021-08-13T11:39:24.410' AS DateTime), 3, CAST(N'2021-08-13T11:39:24.410' AS DateTime), NULL, NULL)
		SET IDENTITY_INSERT [dbo].[ZnodeShipping] OFF
		SET IDENTITY_INSERT [dbo].[ZnodeTaxPortal] ON
		INSERT INTO [dbo].[ZnodeTaxPortal] ([TaxPortalId], [PortalId], [AvataxUrl], [AvalaraAccount], [AvalaraLicense], [AvalaraCompanyCode], [AvalaraFreightIdentifier], [STOCCHUrl], [EntityId], [DivisionId], [FreightTaxGroupCode], [FreightTaxItemCode], [CreatedDate], [ModifiedDate], [CreatedBy], [ModifiedBy], [TaxRuleTypeId], [Custom1], [Custom2], [Custom3], [Custom4], [Custom5], [AvataxIsTaxIncluded]) VALUES (1, 7, N'https://development.avalara.net/', N'1100095552', N'6FF15411B5E9D5EF', N'ZN0022', N'PA020659', NULL, NULL, NULL, NULL, NULL, CAST(N'2019-05-31T15:06:56.200' AS DateTime), CAST(N'2019-05-31T15:06:56.200' AS DateTime), 2, 2, NULL, NULL, NULL, NULL, NULL, NULL, 0)
		INSERT INTO [dbo].[ZnodeTaxPortal] ([TaxPortalId], [PortalId], [AvataxUrl], [AvalaraAccount], [AvalaraLicense], [AvalaraCompanyCode], [AvalaraFreightIdentifier], [STOCCHUrl], [EntityId], [DivisionId], [FreightTaxGroupCode], [FreightTaxItemCode], [CreatedDate], [ModifiedDate], [CreatedBy], [ModifiedBy], [TaxRuleTypeId], [Custom1], [Custom2], [Custom3], [Custom4], [Custom5], [AvataxIsTaxIncluded]) VALUES (2, 8, N'https://development.avalara.net/', N'1100128359', N'e4e58c132a344140', N'Znode', N'PA020659', NULL, NULL, NULL, NULL, NULL, CAST(N'2021-08-17T12:12:42.970' AS DateTime), CAST(N'2021-08-17T12:12:42.970' AS DateTime), 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 0)
		INSERT INTO [dbo].[ZnodeTaxPortal] ([TaxPortalId], [PortalId], [AvataxUrl], [AvalaraAccount], [AvalaraLicense], [AvalaraCompanyCode], [AvalaraFreightIdentifier], [STOCCHUrl], [EntityId], [DivisionId], [FreightTaxGroupCode], [FreightTaxItemCode], [CreatedDate], [ModifiedDate], [CreatedBy], [ModifiedBy], [TaxRuleTypeId], [Custom1], [Custom2], [Custom3], [Custom4], [Custom5], [AvataxIsTaxIncluded]) VALUES (3, 9, N'https://development.avalara.net/', N'1100128359', N'e4e58c132a344140', N'Znode', N'PA020659', NULL, NULL, NULL, NULL, NULL, CAST(N'2021-08-17T12:29:20.057' AS DateTime), CAST(N'2021-08-17T12:29:20.057' AS DateTime), 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 0)
		SET IDENTITY_INSERT [dbo].[ZnodeTaxPortal] OFF
		SET IDENTITY_INSERT [dbo].[ZnodeProfileShipping] ON
		INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (1, 2, 4, 2, '20190603 06:25:57.253', 2, '20190603 06:25:57.253', NULL, NULL)
		INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (2, 2, 2, 2, '20190603 06:25:57.253', 2, '20190603 06:25:57.253', NULL, NULL)
		INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (7, 1, 2, 2, '20190603 06:27:03.163', 2, '20190603 06:27:03.163', NULL, NULL)
		INSERT INTO [dbo].[ZnodeProfileShipping] ([ProfileShippingId], [ProfileId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisplayOrder], [PublishStateId]) VALUES (8, 1, 4, 2, '20190603 06:27:03.163', 2, '20190603 06:27:03.163', NULL, NULL)
		SET IDENTITY_INSERT [dbo].[ZnodeProfileShipping] OFF
		SET IDENTITY_INSERT [dbo].[ZnodePortalSmtpSetting] ON
		INSERT INTO [dbo].[ZnodePortalSmtpSetting] ([PortalSmtpSettingId], [PortalId], [ServerName], [UserName], [Password], [Port], [IsEnableSsl], [FromDisplayName], [FromEmailAddress], [BccEmailAddress], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisableAllEmails]) VALUES (1, 7, N'smtp.gmail.com', N'MTBhuZTIonuEMvpTjbZMysQ9aibbc4A+', N'znode12345', 25, 1, NULL, NULL, NULL, 2, CAST(N'2017-02-08T15:39:36.000' AS DateTime), 2, CAST(N'2017-02-08T15:46:43.000' AS DateTime), 0)
		INSERT INTO [dbo].[ZnodePortalSmtpSetting] ([PortalSmtpSettingId], [PortalId], [ServerName], [UserName], [Password], [Port], [IsEnableSsl], [FromDisplayName], [FromEmailAddress], [BccEmailAddress], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisableAllEmails]) VALUES (2, 8, N'smtp.sendgrid.net', N'th5zP6HMPQaoVz0IHQvKxQ==', N'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', 465, 1, N'Fine Food', N'rj200@yopmail.com', N'rj200@yopmail.com', 2, CAST(N'2021-08-17T11:45:54.557' AS DateTime), 3, CAST(N'2021-09-02T15:28:31.710' AS DateTime), 0)
		INSERT INTO [dbo].[ZnodePortalSmtpSetting] ([PortalSmtpSettingId], [PortalId], [ServerName], [UserName], [Password], [Port], [IsEnableSsl], [FromDisplayName], [FromEmailAddress], [BccEmailAddress], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [DisableAllEmails]) VALUES (3, 9, N'smtp.sendgrid.net', N'th5zP6HMPQaoVz0IHQvKxQ==', N'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', 465, 1, N'SAFETYGear', N'admin@znode.com', NULL, 2, CAST(N'2021-08-17T12:20:57.743' AS DateTime), 3, CAST(N'2021-09-02T18:46:44.150' AS DateTime), 0)
		SET IDENTITY_INSERT [dbo].[ZnodePortalSmtpSetting] OFF
		SET IDENTITY_INSERT [dbo].[ZnodePortalShipping] ON
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (18, 7, 2, 2, CAST(N'2019-04-25T00:37:07.800' AS DateTime), 2, CAST(N'2019-04-25T00:37:07.800' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (20, 7, 4, 2, CAST(N'2019-04-25T00:37:07.800' AS DateTime), 2, CAST(N'2019-04-25T00:37:07.800' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (24, 8, 2, 3, CAST(N'2021-08-17T12:09:26.750' AS DateTime), 3, CAST(N'2021-08-17T12:09:26.750' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (25, 8, 6, 3, CAST(N'2021-08-17T12:09:26.750' AS DateTime), 3, CAST(N'2021-08-17T12:09:26.750' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (26, 8, 4, 3, CAST(N'2021-08-17T12:09:26.750' AS DateTime), 3, CAST(N'2021-08-17T12:09:26.750' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (29, 9, 2, 3, CAST(N'2021-08-17T12:27:43.880' AS DateTime), 3, CAST(N'2021-08-17T12:27:43.880' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (30, 9, 4, 3, CAST(N'2021-08-17T12:27:43.880' AS DateTime), 3, CAST(N'2021-08-17T12:27:43.880' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodePortalShipping] ([PortalShippingId], [PortalId], [ShippingId], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (31, 9, 6, 3, CAST(N'2021-08-17T12:27:43.880' AS DateTime), 3, CAST(N'2021-08-17T12:27:43.880' AS DateTime), 3)
		SET IDENTITY_INSERT [dbo].[ZnodePortalShipping] OFF
		SET IDENTITY_INSERT [dbo].[ZnodeShippingPortal] ON
		INSERT INTO [dbo].[ZnodeShippingPortal] ([ShippingPortalId], [PortalId], [ShippingOriginAddress1], [ShippingOriginAddress2], [ShippingOriginCity], [ShippingOriginStateCode], [ShippingOriginZipCode], [ShippingOriginCountryCode], [ShippingOriginPhone], [FedExAccountNumber], [FedExLTLAccountNumber], [FedExMeterNumber], [FedExProductionKey], [FedExSecurityCode], [FedExDropoffType], [FedExPackagingType], [FedExUseDiscountRate], [FedExAddInsurance], [UPSUserName], [UPSPassword], [UPSKey], [LTLUPSAccessLicenseNumber], [LTLUPSUsername], [LTLUPSPassword], [LTLUPSAccountNumber], [UPSDropoffType], [UPSPackagingType], [IsUseWarehouseAddress], [USPSShippingAPIURL], [USPSWebToolsUserID], [PackageWeightLimit], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (4, 7, N'1225 Discovery Parkway', N'Suite 155', N'Milwaukee', N'WI', N'53226', N'US', N'+1-855-927-8434', N'8UHG9VP6OrV2qSp688jJhg==', NULL, N'IKOpkTC+qbQn04Mbl/BZ5Q==', N'wOWfd2sWGxYzHAWUDRBx0XeB1YEA+2pJ', N'q8oM2zKjE36pNqNC6mYy7sYaZfYh9vNqja4zn+gIkR8=', N'BUSINESS_SERVICE_CENTER', N'YOUR_PACKAGING', 1, 1, N'l8PcAXBZbWxARbbxtIQwvQ==', N'A3SRKCOHX6pyizEU8k4bWZnXggUHDVa+', N'MDA/u+KFtCOLLUNrXRb685v+Ug8hRdQi', NULL, NULL, NULL, NULL, N'Regular Daily Pickup', N'01', 1, N'http://Production.ShippingAPIs.com/ShippingAPI.dll', N'834ENCOR4758', CAST(65.000000 AS Numeric(28, 6)), 2, CAST(N'2019-04-25T00:34:36.657' AS DateTime), 2, CAST(N'2019-06-03T06:31:07.890' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodeShippingPortal] ([ShippingPortalId], [PortalId], [ShippingOriginAddress1], [ShippingOriginAddress2], [ShippingOriginCity], [ShippingOriginStateCode], [ShippingOriginZipCode], [ShippingOriginCountryCode], [ShippingOriginPhone], [FedExAccountNumber], [FedExLTLAccountNumber], [FedExMeterNumber], [FedExProductionKey], [FedExSecurityCode], [FedExDropoffType], [FedExPackagingType], [FedExUseDiscountRate], [FedExAddInsurance], [UPSUserName], [UPSPassword], [UPSKey], [LTLUPSAccessLicenseNumber], [LTLUPSUsername], [LTLUPSPassword], [LTLUPSAccountNumber], [UPSDropoffType], [UPSPackagingType], [IsUseWarehouseAddress], [USPSShippingAPIURL], [USPSWebToolsUserID], [PackageWeightLimit], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (5, 8, N'1225 Discovery Parkway', N'Suite 155', N'Milwaukee', N'WI', N'53226', N'US', N'+1-855-927-8434', N'8UHG9VP6OrV2qSp688jJhg==', NULL, N'IKOpkTC+qbQn04Mbl/BZ5Q==', N'wOWfd2sWGxYzHAWUDRBx0XeB1YEA+2pJ', N'q8oM2zKjE36pNqNC6mYy7sYaZfYh9vNqja4zn+gIkR8=', N'BUSINESS_SERVICE_CENTER', N'YOUR_PACKAGING', 1, 1, N'l8PcAXBZbWxARbbxtIQwvQ==', N'A3SRKCOHX6pyizEU8k4bWZnXggUHDVa+', N'MDA/u+KFtCOLLUNrXRb685v+Ug8hRdQi', NULL, NULL, NULL, NULL, N'Regular Daily Pickup', N'01', 1, N'http://Production.ShippingAPIs.com/ShippingAPI.dll', N'834ENCOR4758', CAST(65.000000 AS Numeric(28, 6)), 3, CAST(N'2021-08-17T12:08:12.157' AS DateTime), 3, CAST(N'2021-08-17T12:08:50.053' AS DateTime), 3)
		INSERT INTO [dbo].[ZnodeShippingPortal] ([ShippingPortalId], [PortalId], [ShippingOriginAddress1], [ShippingOriginAddress2], [ShippingOriginCity], [ShippingOriginStateCode], [ShippingOriginZipCode], [ShippingOriginCountryCode], [ShippingOriginPhone], [FedExAccountNumber], [FedExLTLAccountNumber], [FedExMeterNumber], [FedExProductionKey], [FedExSecurityCode], [FedExDropoffType], [FedExPackagingType], [FedExUseDiscountRate], [FedExAddInsurance], [UPSUserName], [UPSPassword], [UPSKey], [LTLUPSAccessLicenseNumber], [LTLUPSUsername], [LTLUPSPassword], [LTLUPSAccountNumber], [UPSDropoffType], [UPSPackagingType], [IsUseWarehouseAddress], [USPSShippingAPIURL], [USPSWebToolsUserID], [PackageWeightLimit], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [PublishStateId]) VALUES (6, 9, N'1225 Discovery Parkway', N'Suite 155', N'Milwaukee', N'WI', N'53226', N'US', N'18559278434', N'8UHG9VP6OrV2qSp688jJhg==', NULL, N'IKOpkTC+qbQn04Mbl/BZ5Q==', N'wOWfd2sWGxYzHAWUDRBx0XeB1YEA+2pJ', N'q8oM2zKjE36pNqNC6mYy7sYaZfYh9vNqja4zn+gIkR8=', N'BUSINESS_SERVICE_CENTER', N'YOUR_PACKAGING', 1, 1, N'l8PcAXBZbWxARbbxtIQwvQ==', N'A3SRKCOHX6pyizEU8k4bWZnXggUHDVa+', N'MDA/u+KFtCOLLUNrXRb685v+Ug8hRdQi', NULL, NULL, NULL, NULL, N'Regular Daily Pickup', N'01', 1, N'http://Production.ShippingAPIs.com/ShippingAPI.dll', N'834ENCOR4758', CAST(65.000000 AS Numeric(28, 6)), 3, CAST(N'2021-08-17T12:27:00.560' AS DateTime), 3, CAST(N'2021-08-17T12:27:33.823' AS DateTime), 3)
		SET IDENTITY_INSERT [dbo].[ZnodeShippingPortal] OFF
	END
END
