IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'SynonymCode' AND TABLE_NAME = 'ZnodeSearchSynonyms')
BEGIN
	UPDATE ZnodeSearchSynonyms SET SynonymCode = SearchSynonymsId WHERE SynonymCode IS NULL
END
GO
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'SynonymCode' AND TABLE_NAME = 'ZnodeSearchSynonyms')
BEGIN
	ALTER TABLE ZnodeSearchSynonyms ALTER COLUMN SynonymCode NVARCHAR(100) NOT NULL
END