Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'webstoreentity','PortalId,LocaleId,PublishState',1,0,'store',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'webstoreentity' and DelimitedColumns = 'PortalId,LocaleId,PublishState' and EntityType = 'store')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'contentpageconfigentity','PortalId,IsActive,ProfileId,VersionId',1,0,'store',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'contentpageconfigentity' and DelimitedColumns = 'PortalId,IsActive,ProfileId,VersionId' and EntityType = 'store')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'categoryentity','DisplayOrder,ZnodeCategoryId,ZnodeCatalogId,LocaleId,VersionId,IsActive',1,0,'Catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'categoryentity' and DelimitedColumns = 'DisplayOrder,ZnodeCategoryId,ZnodeCatalogId,LocaleId,VersionId,IsActive' and EntityType = 'Catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'categoryentity','IsActive,VersionId,ZnodeCatalogId,ZnodeCategoryId',1,1,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'categoryentity' and DelimitedColumns = 'IsActive,VersionId,ZnodeCatalogId,ZnodeCategoryId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'logmessageentity','CreatedDate',1,0,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'logmessageentity' and DelimitedColumns = 'CreatedDate' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'versionentity','ZnodeCatalogId,RevisionType,LocaleId',1,0,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'versionentity' and DelimitedColumns = 'ZnodeCatalogId,RevisionType,LocaleId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'configurableproductentity','ZnodeProductId,VersionId',1,0,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'configurableproductentity' and DelimitedColumns = 'ZnodeProductId,VersionId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'configurableproductentity','VersionId,ZnodeProductId',1,1,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'configurableproductentity' and DelimitedColumns = 'VersionId,ZnodeProductId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'seoentity','PortalId,SEOTypeName,LocaleId,VersionId,SEOCode',1,0,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'seoentity' and DelimitedColumns = 'PortalId,SEOTypeName,LocaleId,VersionId,SEOCode' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'seoentity','PortalId,SEOUrl,VersionId',1,1,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'seoentity' and DelimitedColumns = 'PortalId,SEOUrl,VersionId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'seoentity','PortalId,SEOCode,SEOTypeName,SEOUrl,VersionId',1,1,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'seoentity' and DelimitedColumns = 'PortalId,SEOCode,SEOTypeName,SEOUrl,VersionId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'addonentity','DisplayOrder,ZnodeProductId,LocaleId,VersionId,RequiredType',1,0,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'addonentity' and DelimitedColumns = 'DisplayOrder,ZnodeProductId,LocaleId,VersionId,RequiredType' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'productentity','ZnodeProductId,SKULower,ZnodeCatalogId,ZnodeCategoryIds,LocaleId,ProductIndex,IsActive,VersionId',1,0,'catalog',2,getdate(),2,getdate() where not exists( select * from ZnodeMongoIndex where CollectionName = 'productentity' and DelimitedColumns = 'ZnodeProductId,SKULower,ZnodeCatalogId,ZnodeCategoryIds,LocaleId,ProductIndex,IsActive,VersionId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'productentity','IsActive, LocaleId,VersionId,ZnodeCatalogId,ZnodeProductId',1,1,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'productentity' and DelimitedColumns = 'IsActive, LocaleId,VersionId,ZnodeCatalogId,ZnodeProductId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'productentity','IsActive,LocaleId,VersionId,ZnodeProductId',1,1,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'productentity' and DelimitedColumns = 'IsActive,LocaleId,VersionId,ZnodeProductId' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'productentity','LocaleId,ZnodeCatalogId,SKU',1,1,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'productentity' and DelimitedColumns = 'LocaleId,ZnodeCatalogId,SKU' and EntityType = 'catalog')
Insert Into ZnodeMongoIndex(CollectionName,DelimitedColumns,IsAscending,IsCompoundIndex,EntityType,Createdby,CreatedDate,ModifiedBy,ModifiedDate)
select 'textwidgetentity','LocaleId,PortalId,VersionId',1,0,'catalog',2,getdate(),2,getdate() 
where not exists( select * from ZnodeMongoIndex where CollectionName = 'textwidgetentity' and DelimitedColumns = 'LocaleId,PortalId,VersionId' and EntityType = 'catalog')