//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MediaFolderUserShare : ZnodeEntityBaseModel
    {
        public int MediaPathId { get; set; }
        public string PathName { get; set; }
        public Nullable<int> ParentMediaPathId { get; set; }
    }
}
