//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetObjectColumnList : ZnodeEntityBaseModel
    {
        public string ObjectName { get; set; }
        public int columnId { get; set; }
        public string ColumnName { get; set; }
        public string DataType { get; set; }
    }
}
