//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PimAttributeGroupbyFamily : ZnodeEntityBaseModel
    {
        public int PimAttributeFamilyId { get; set; }
        public string GroupCode { get; set; }
        public string AttributeGroupName { get; set; }
        public int PimAttributeGroupId { get; set; }
        public string GroupType { get; set; }
    }
}
