//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetContentPageDetails : ZnodeEntityBaseModel
    {
        public int CMSContentPagesId { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeywords { get; set; }
        public string SEOTitle { get; set; }
        public string SEOUrl { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsRedirect { get; set; }
        public string StoreName { get; set; }
        public int CMSTemplateId { get; set; }
        public string MetaInformation { get; set; }
        public int PortalId { get; set; }
        public Nullable<int> CMSContentPageGroupId { get; set; }
        public Nullable<int> LocaleId { get; set; }
        public string CanonicalURL { get; set; }
        public string RobotTag { get; set; }
    }
}
