//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ZnodeTouchPointConfiguration : ZnodeEntityBaseModel
    {
        public int TouchPointConfigurationId { get; set; }
        public Nullable<int> SchedulerName { get; set; }
        public Nullable<int> Interface { get; set; }
        public Nullable<int> ConnectorTouchPoints { get; set; }
        public Nullable<int> IsEnabled { get; set; }
        public Nullable<int> Triggers { get; set; }
        public Nullable<int> NextRunTime { get; set; }
        public Nullable<int> LastRunResult { get; set; }
        public Nullable<int> SchedulerCreatedDate { get; set; }
    }
}
