//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetOmsOrderNotes : ZnodeEntityBaseModel
    {
        public string UserName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> OmsOrderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> OmsOrderDetailsId { get; set; }
        public Nullable<int> OmsQuoteId { get; set; }
    }
}
