//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CategoryUnAssociatedProduct : ZnodeEntityBaseModel
    {
        public Nullable<int> PimCategoryProductId { get; set; }
        public Nullable<int> PimCategoryId { get; set; }
        public Nullable<int> PimProductId { get; set; }
        public int DisplayOrder { get; set; }
        public int Status { get; set; }
        public string ProductName { get; set; }
        public string ImagePath { get; set; }
        public int LocaleId { get; set; }
    }
}
