//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PimCategoryAttributeValueLocale : ZnodeEntityBaseModel
    {
        public int PimCategoryAttributeValueId { get; set; }
        public Nullable<int> PimCategoryId { get; set; }
        public Nullable<int> PimAttributeFamilyId { get; set; }
        public Nullable<int> PimAttributeId { get; set; }
        public Nullable<int> PimAttributeDefaultValueId { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CategoryValue { get; set; }
        public Nullable<int> LocaleId { get; set; }
    }
}
