//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetRMASearchRequest : ZnodeEntityBaseModel
    {
        public int RmaRequestId { get; set; }
        public string RequestNumber { get; set; }
        public Nullable<int> OmsOrderId { get; set; }
        public Nullable<int> OmsOrderDetailsId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public Nullable<int> RmaRequestStatusId { get; set; }
        public string RequestStatus { get; set; }
        public string BillingFirstName { get; set; }
        public string BillingLastName { get; set; }
        public System.DateTime RequestDate { get; set; }
        public decimal Total { get; set; }
        public decimal TaxCost { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Discount { get; set; }
        public string StoreName { get; set; }
        public string CustomerName { get; set; }
        public string UserName { get; set; }
        public string OrderNumber { get; set; }
    }
}
