//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PimCategoryDetail : ZnodeEntityBaseModel
    {
        public int PimCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Status { get; set; }
        public string CategoryImage { get; set; }
        public Nullable<int> LocaleId { get; set; }
        public string AttributeFamilyName { get; set; }
    }
}
