//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishMessageEntity : ZnodeEntityBaseModel
    {
        public int PublishMessageEntityId { get; set; }
        public int VersionId { get; set; }
        public Nullable<System.DateTime> PublishStartTime { get; set; }
        public int LocaleId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string MessageKey { get; set; }
        public string Message { get; set; }
        public string Area { get; set; }
    }
}
