//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeImpersonationLog : ZnodeEntityBaseModel
    {
        public int ImpersonationLogId { get; set; }
        public int PortalId { get; set; }
        public Nullable<int> CSRId { get; set; }
        public Nullable<int> WebstoreuserId { get; set; }
        public string ActivityType { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string OperationType { get; set; }
    
        public virtual ZnodePortal ZnodePortal { get; set; }
    }
}
