//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeGlobalAttributeFamily : ZnodeEntityBaseModel
    {
        public ZnodeGlobalAttributeFamily()
        {
            this.ZnodeGlobalAttributeFamilyLocales = new HashSet<ZnodeGlobalAttributeFamilyLocale>();
            this.ZnodeGlobalEntityFamilyMappers = new HashSet<ZnodeGlobalEntityFamilyMapper>();
            this.ZnodeGlobalFamilyGroupMappers = new HashSet<ZnodeGlobalFamilyGroupMapper>();
        }
    
        public int GlobalAttributeFamilyId { get; set; }
        public string FamilyCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsSystemDefined { get; set; }
        public int GlobalEntityId { get; set; }
    
        public virtual ZnodeGlobalEntity ZnodeGlobalEntity { get; set; }
        public virtual ICollection<ZnodeGlobalAttributeFamilyLocale> ZnodeGlobalAttributeFamilyLocales { get; set; }
        public virtual ICollection<ZnodeGlobalEntityFamilyMapper> ZnodeGlobalEntityFamilyMappers { get; set; }
        public virtual ICollection<ZnodeGlobalFamilyGroupMapper> ZnodeGlobalFamilyGroupMappers { get; set; }
    }
}
