//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCustomReportFilter : ZnodeEntityBaseModel
    {
        public int CustomReportFilterId { get; set; }
        public int CustomReportTemplateId { get; set; }
        public string FilterName { get; set; }
        public string Action { get; set; }
        public string FilterValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeCustomReportTemplate ZnodeCustomReportTemplate { get; set; }
    }
}
