//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCulture : ZnodeEntityBaseModel
    {
        public ZnodeCulture()
        {
            this.ZnodePortalUnits = new HashSet<ZnodePortalUnit>();
            this.ZnodePriceLists = new HashSet<ZnodePriceList>();
            this.ZnodeShippings = new HashSet<ZnodeShipping>();
        }
    
        public int CultureId { get; set; }
        public string CultureCode { get; set; }
        public string CultureName { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Symbol { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeCurrency ZnodeCurrency { get; set; }
        public virtual ICollection<ZnodePortalUnit> ZnodePortalUnits { get; set; }
        public virtual ICollection<ZnodePriceList> ZnodePriceLists { get; set; }
        public virtual ICollection<ZnodeShipping> ZnodeShippings { get; set; }
    }
}
