//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsTaxOrderSummary : ZnodeEntityBaseModel
    {
        public int OmsTaxOrderSummaryId { get; set; }
        public Nullable<int> OmsOrderDetailsId { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string TaxName { get; set; }
        public string TaxTypeName { get; set; }
    
        public virtual ZnodeOmsOrderDetail ZnodeOmsOrderDetail { get; set; }
    }
}
