//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsQuotePersonalizeItem : ZnodeEntityBaseModel
    {
        public int OmsQuotePersonalizeItemId { get; set; }
        public int OmsQuoteLineItemId { get; set; }
        public string PersonalizeCode { get; set; }
        public string PersonalizeValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string DesignId { get; set; }
        public string ThumbnailURL { get; set; }
    }
}
