//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePaymentSetting : ZnodeEntityBaseModel
    {
        public ZnodePaymentSetting()
        {
            this.ZnodePortalPaymentSettings = new HashSet<ZnodePortalPaymentSetting>();
            this.ZnodePortalPaymentSettings1 = new HashSet<ZnodePortalPaymentSetting>();
            this.ZnodeOmsQuotes = new HashSet<ZnodeOmsQuote>();
            this.ZnodeProfilePaymentSettings = new HashSet<ZnodeProfilePaymentSetting>();
            this.ZnodeOmsOrderDetails = new HashSet<ZnodeOmsOrderDetail>();
            this.ZnodeRmaReturnPaymentDetails = new HashSet<ZnodeRmaReturnPaymentDetail>();
        }
    
        public int PaymentSettingId { get; set; }
        public int PaymentApplicationSettingId { get; set; }
        public int PaymentTypeId { get; set; }
        public Nullable<int> PaymentGatewayId { get; set; }
        public string PaymentName { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsTestMode { get; set; }
        public bool IsPoDocUploadEnable { get; set; }
        public bool IsPoDocRequire { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string PaymentDisplayName { get; set; }
        public bool IsCaptureDisable { get; set; }
        public string PaymentCode { get; set; }
        public bool IsBillingAddressOptional { get; set; }
        public bool IsOABRequired { get; set; }
      
        public virtual ZnodePaymentGateway ZnodePaymentGateway { get; set; }
        public virtual ZnodePaymentType ZnodePaymentType { get; set; }
        public virtual ICollection<ZnodePortalPaymentSetting> ZnodePortalPaymentSettings { get; set; }
        public virtual ICollection<ZnodePortalPaymentSetting> ZnodePortalPaymentSettings1 { get; set; }
        public virtual ICollection<ZnodeOmsQuote> ZnodeOmsQuotes { get; set; }
        public virtual ICollection<ZnodeProfilePaymentSetting> ZnodeProfilePaymentSettings { get; set; }
        public virtual ICollection<ZnodeOmsOrderDetail> ZnodeOmsOrderDetails { get; set; }
        public virtual ICollection<ZnodeRmaReturnPaymentDetail> ZnodeRmaReturnPaymentDetails { get; set; }
    }
}
