//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePimProduct : ZnodeEntityBaseModel
    {
        public ZnodePimProduct()
        {
            this.ZnodeBrandProducts = new HashSet<ZnodeBrandProduct>();
            this.ZnodePimAddonGroupProducts = new HashSet<ZnodePimAddonGroupProduct>();
            this.ZnodePimAddOnProducts = new HashSet<ZnodePimAddOnProduct>();
            this.ZnodePimAddOnProductDetails = new HashSet<ZnodePimAddOnProductDetail>();
            this.ZnodePimAttributeValues = new HashSet<ZnodePimAttributeValue>();
            this.ZnodePimCategoryProducts = new HashSet<ZnodePimCategoryProduct>();
            this.ZnodePimConfigureProductAttributes = new HashSet<ZnodePimConfigureProductAttribute>();
            this.ZnodePimCustomFields = new HashSet<ZnodePimCustomField>();
            this.ZnodePimProductImages = new HashSet<ZnodePimProductImage>();
            this.ZnodePimLinkProductDetails = new HashSet<ZnodePimLinkProductDetail>();
            this.ZnodePimLinkProductDetails1 = new HashSet<ZnodePimLinkProductDetail>();
            this.ZnodePimProductTypeAssociations = new HashSet<ZnodePimProductTypeAssociation>();
            this.ZnodePimProductTypeAssociations1 = new HashSet<ZnodePimProductTypeAssociation>();
        }
    
        public int PimProductId { get; set; }
        public Nullable<int> PimAttributeFamilyId { get; set; }
        public string ExternalId { get; set; }
        public Nullable<byte> IsProductPublish { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<byte> PublishStateId { get; set; }
    
        public virtual ICollection<ZnodeBrandProduct> ZnodeBrandProducts { get; set; }
        public virtual ICollection<ZnodePimAddonGroupProduct> ZnodePimAddonGroupProducts { get; set; }
        public virtual ICollection<ZnodePimAddOnProduct> ZnodePimAddOnProducts { get; set; }
        public virtual ICollection<ZnodePimAddOnProductDetail> ZnodePimAddOnProductDetails { get; set; }
        public virtual ZnodePimAttributeFamily ZnodePimAttributeFamily { get; set; }
        public virtual ICollection<ZnodePimAttributeValue> ZnodePimAttributeValues { get; set; }
        public virtual ICollection<ZnodePimCategoryProduct> ZnodePimCategoryProducts { get; set; }
        public virtual ICollection<ZnodePimConfigureProductAttribute> ZnodePimConfigureProductAttributes { get; set; }
        public virtual ICollection<ZnodePimCustomField> ZnodePimCustomFields { get; set; }
        public virtual ZnodePublishState ZnodePublishState { get; set; }
        public virtual ICollection<ZnodePimProductImage> ZnodePimProductImages { get; set; }
        public virtual ICollection<ZnodePimLinkProductDetail> ZnodePimLinkProductDetails { get; set; }
        public virtual ICollection<ZnodePimLinkProductDetail> ZnodePimLinkProductDetails1 { get; set; }
        public virtual ICollection<ZnodePimProductTypeAssociation> ZnodePimProductTypeAssociations { get; set; }
        public virtual ICollection<ZnodePimProductTypeAssociation> ZnodePimProductTypeAssociations1 { get; set; }
    }
}
