//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsOrderState : ZnodeEntityBaseModel
    {
        public ZnodeOmsOrderState()
        {
            this.ZnodeOmsOrderLineItems = new HashSet<ZnodeOmsOrderLineItem>();
            this.ZnodeOmsOrderLineItemsShippings = new HashSet<ZnodeOmsOrderLineItemsShipping>();
            this.ZnodeOmsQuotes = new HashSet<ZnodeOmsQuote>();
            this.ZnodePortals = new HashSet<ZnodePortal>();
            this.ZnodeOmsOrderDetails = new HashSet<ZnodeOmsOrderDetail>();
        }
    
        public int OmsOrderStateId { get; set; }
        public string OrderStateName { get; set; }
        public bool IsShowToCustomer { get; set; }
        public Nullable<bool> IsAccountStatus { get; set; }
        public int DisplayOrder { get; set; }
        public string Description { get; set; }
        public bool IsEdit { get; set; }
        public bool IsSendEmail { get; set; }
        public Nullable<bool> IsOrderState { get; set; }
        public Nullable<bool> IsOrderLineItemState { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<bool> IsQuoteState { get; set; }
    
        public virtual ICollection<ZnodeOmsOrderLineItem> ZnodeOmsOrderLineItems { get; set; }
        public virtual ICollection<ZnodeOmsOrderLineItemsShipping> ZnodeOmsOrderLineItemsShippings { get; set; }
        public virtual ICollection<ZnodeOmsQuote> ZnodeOmsQuotes { get; set; }
        public virtual ICollection<ZnodePortal> ZnodePortals { get; set; }
        public virtual ICollection<ZnodeOmsOrderDetail> ZnodeOmsOrderDetails { get; set; }
    }
}
