//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeMenu : ZnodeEntityBaseModel
    {
        public ZnodeMenu()
        {
            this.ZnodeMenu1 = new HashSet<ZnodeMenu>();
            this.ZnodeMenuActionsPermissions = new HashSet<ZnodeMenuActionsPermission>();
            this.ZnodeRoleMenus = new HashSet<ZnodeRoleMenu>();
        }
    
        public int MenuId { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> MenuSequence { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string CSSClassName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeMenu> ZnodeMenu1 { get; set; }
        public virtual ZnodeMenu ZnodeMenu2 { get; set; }
        public virtual ICollection<ZnodeMenuActionsPermission> ZnodeMenuActionsPermissions { get; set; }
        public virtual ICollection<ZnodeRoleMenu> ZnodeRoleMenus { get; set; }
    }
}
