//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZnodePublish_Entities : DbContext
    {
        public ZnodePublish_Entities()
            : base("name=ZnodePublish_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ZnodePublishWebstoreEntity> ZnodePublishWebstoreEntities { get; set; }
        public virtual DbSet<ZnodePublishContentPageConfigEntity> ZnodePublishContentPageConfigEntities { get; set; }
        public virtual DbSet<ZnodePublishErrorLogEntity> ZnodePublishErrorLogEntities { get; set; }
        public virtual DbSet<ZnodePublishMessageEntity> ZnodePublishMessageEntities { get; set; }
        public virtual DbSet<ZnodePublishPortalBrandEntity> ZnodePublishPortalBrandEntities { get; set; }
        public virtual DbSet<ZnodePublishCategoryEntity> ZnodePublishCategoryEntities { get; set; }
        public virtual DbSet<ZnodePublishConfigurableProductEntity> ZnodePublishConfigurableProductEntities { get; set; }
        public virtual DbSet<ZnodePublishGlobalMessageEntity> ZnodePublishGlobalMessageEntities { get; set; }
        public virtual DbSet<ZnodePublishGlobalVersionEntity> ZnodePublishGlobalVersionEntities { get; set; }
        public virtual DbSet<ZnodePublishMediaWidgetEntity> ZnodePublishMediaWidgetEntities { get; set; }
        public virtual DbSet<ZnodePublishPortalCustomCssEntity> ZnodePublishPortalCustomCssEntities { get; set; }
        public virtual DbSet<ZnodePublishPortalErrorLogEntity> ZnodePublishPortalErrorLogEntities { get; set; }
        public virtual DbSet<ZnodePublishPortalGlobalAttributeEntity> ZnodePublishPortalGlobalAttributeEntities { get; set; }
        public virtual DbSet<ZnodePublishPreviewLogEntity> ZnodePublishPreviewLogEntities { get; set; }
        public virtual DbSet<ZnodePublishProductPageEntity> ZnodePublishProductPageEntities { get; set; }
        public virtual DbSet<ZnodePublishSearchWidgetEntity> ZnodePublishSearchWidgetEntities { get; set; }
        public virtual DbSet<ZnodePublishSeoEntity> ZnodePublishSeoEntities { get; set; }
        public virtual DbSet<ZnodePublishTextWidgetEntity> ZnodePublishTextWidgetEntities { get; set; }
        public virtual DbSet<ZnodePublishVersionEntity> ZnodePublishVersionEntities { get; set; }
        public virtual DbSet<ZnodePublishWidgetBrandEntity> ZnodePublishWidgetBrandEntities { get; set; }
        public virtual DbSet<ZnodePublishWidgetCategoryEntity> ZnodePublishWidgetCategoryEntities { get; set; }
        public virtual DbSet<ZnodePublishWidgetProductEntity> ZnodePublishWidgetProductEntities { get; set; }
        public virtual DbSet<ZnodePublishWidgetSliderBannerEntity> ZnodePublishWidgetSliderBannerEntities { get; set; }
        public virtual DbSet<ZnodePublishWidgetTitleEntity> ZnodePublishWidgetTitleEntities { get; set; }
        public virtual DbSet<ZnodePublishBlogNewsEntity> ZnodePublishBlogNewsEntities { get; set; }
        public virtual DbSet<ZnodePublishBundleProductEntity> ZnodePublishBundleProductEntities { get; set; }
        public virtual DbSet<ZnodePublishAddonEntity> ZnodePublishAddonEntities { get; set; }
        public virtual DbSet<ZnodePublishCatalogAttributeEntity> ZnodePublishCatalogAttributeEntities { get; set; }
        public virtual DbSet<ZnodePublishCatalogEntity> ZnodePublishCatalogEntities { get; set; }
        public virtual DbSet<ZnodePublishGroupProductEntity> ZnodePublishGroupProductEntities { get; set; }
        public virtual DbSet<ZnodePublishProgressNotifierEntity> ZnodePublishProgressNotifierEntities { get; set; }
        public virtual DbSet<ZnodePublishProductEntity> ZnodePublishProductEntities { get; set; }
        public virtual DbSet<ZnodePublishContainerWidgetEntity> ZnodePublishContainerWidgetEntities { get; set; }
        public virtual DbSet<ZnodePublishContentContainerEntity> ZnodePublishContentContainerEntities { get; set; }
        public virtual DbSet<ZnodePublishSearchProfileEntity> ZnodePublishSearchProfileEntities { get; set; }
    }
}
