//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeWarehouse : ZnodeEntityBaseModel
    {
        public ZnodeWarehouse()
        {
            this.ZnodeInventories = new HashSet<ZnodeInventory>();
            this.ZnodeOmsOrderWarehouses = new HashSet<ZnodeOmsOrderWarehouse>();
            this.ZnodePortalAlternateWarehouses = new HashSet<ZnodePortalAlternateWarehouse>();
            this.ZnodePortalWarehouses = new HashSet<ZnodePortalWarehouse>();
            this.ZnodeWarehouseAddresses = new HashSet<ZnodeWarehouseAddress>();
        }
    
        public int WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeInventory> ZnodeInventories { get; set; }
        public virtual ICollection<ZnodeOmsOrderWarehouse> ZnodeOmsOrderWarehouses { get; set; }
        public virtual ICollection<ZnodePortalAlternateWarehouse> ZnodePortalAlternateWarehouses { get; set; }
        public virtual ICollection<ZnodePortalWarehouse> ZnodePortalWarehouses { get; set; }
        public virtual ICollection<ZnodeWarehouseAddress> ZnodeWarehouseAddresses { get; set; }
    }
}
