//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsOrderLineItemsShipping : ZnodeEntityBaseModel
    {
        public int OmsOrderLineItemsShippingId { get; set; }
        public Nullable<int> OmsOrderId { get; set; }
        public Nullable<int> OmsOrderLineItemsId { get; set; }
        public Nullable<int> OrderLineItemStateId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<decimal> TaxCost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeOmsOrderLineItem ZnodeOmsOrderLineItem { get; set; }
        public virtual ZnodeOmsOrderState ZnodeOmsOrderState { get; set; }
        public virtual ZnodeOmsOrder ZnodeOmsOrder { get; set; }
    }
}
