//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeMediaServerMaster : ZnodeEntityBaseModel
    {
        public ZnodeMediaServerMaster()
        {
            this.ZnodeMediaConfigurations = new HashSet<ZnodeMediaConfiguration>();
        }
    
        public int MediaServerMasterId { get; set; }
        public string ServerName { get; set; }
        public string PartialViewName { get; set; }
        public Nullable<bool> IsOtherServer { get; set; }
        public string ThumbnailFolderName { get; set; }
        public string ClassName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeMediaConfiguration> ZnodeMediaConfigurations { get; set; }
    }
}
