//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePimAttributeValue : ZnodeEntityBaseModel
    {
        public ZnodePimAttributeValue()
        {
            this.ZnodePimAttributeValueLocales = new HashSet<ZnodePimAttributeValueLocale>();
        }
    
        public int PimAttributeValueId { get; set; }
        public Nullable<int> PimAttributeFamilyId { get; set; }
        public Nullable<int> PimProductId { get; set; }
        public Nullable<int> PimAttributeId { get; set; }
        public Nullable<int> PimAttributeDefaultValueId { get; set; }
        public string AttributeValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodePimAttribute ZnodePimAttribute { get; set; }
        public virtual ZnodePimAttributeDefaultValue ZnodePimAttributeDefaultValue { get; set; }
        public virtual ZnodePimAttributeFamily ZnodePimAttributeFamily { get; set; }
        public virtual ZnodePimProduct ZnodePimProduct { get; set; }
        public virtual ICollection<ZnodePimAttributeValueLocale> ZnodePimAttributeValueLocales { get; set; }
    }
}
