//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishErrorLogEntity : ZnodeEntityBaseModel
    {
        public int PublishErrorLogEntityId { get; set; }
        public string EntityName { get; set; }
        public string ErrorDescription { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string VersionId { get; set; }
    }
}
