//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCMSArea : ZnodeEntityBaseModel
    {
        public ZnodeCMSArea()
        {
            this.ZnodeCMSAreaMessageKeys = new HashSet<ZnodeCMSAreaMessageKey>();
        }
    
        public int CMSAreaId { get; set; }
        public string AreaName { get; set; }
        public bool IsWidgetArea { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeCMSAreaMessageKey> ZnodeCMSAreaMessageKeys { get; set; }
    }
}
