//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeRmaReturnLineItem : ZnodeEntityBaseModel
    {
        public ZnodeRmaReturnLineItem()
        {
            this.ZnodeRmaReturnPaymentRefunds = new HashSet<ZnodeRmaReturnPaymentRefund>();
        }
    
        public int RmaReturnLineItemsId { get; set; }
        public int RmaReturnDetailsId { get; set; }
        public int OmsOrderLineItemsId { get; set; }
        public Nullable<int> RmaReasonForReturnId { get; set; }
        public int OrderLineItemRelationshipTypeId { get; set; }
        public string RmaReasonForReturn { get; set; }
        public string Sku { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal ExpectedReturnQuantity { get; set; }
        public Nullable<decimal> ReturnedQuantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public bool ShipSeparately { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public int RmaReturnStateId { get; set; }
        public bool IsActive { get; set; }
        public bool IsShippingReturn { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public string ReturnTypeCode { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> OmsReturnOrderLineItemsId { get; set; }
    
        public virtual ZnodeOmsOrderLineItemRelationshipType ZnodeOmsOrderLineItemRelationshipType { get; set; }
        public virtual ZnodeOmsOrderLineItem ZnodeOmsOrderLineItem { get; set; }
        public virtual ZnodeRmaReasonForReturn ZnodeRmaReasonForReturn { get; set; }
        public virtual ZnodeRmaReturnState ZnodeRmaReturnState { get; set; }
        public virtual ICollection<ZnodeRmaReturnPaymentRefund> ZnodeRmaReturnPaymentRefunds { get; set; }
        public virtual ZnodeOmsOrderLineItem ZnodeOmsOrderLineItem1 { get; set; }
        public virtual ZnodeRmaReturnDetail ZnodeRmaReturnDetail { get; set; }
    }
}
