//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePortalGlobalAttributeValueLocale : ZnodeEntityBaseModel
    {
        public int PortalGlobalAttributeValueLocaleId { get; set; }
        public int PortalGlobalAttributeValueId { get; set; }
        public int LocaleId { get; set; }
        public string AttributeValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> GlobalAttributeDefaultValueId { get; set; }
        public Nullable<int> MediaId { get; set; }
        public string MediaPath { get; set; }
    
        public virtual ZnodeMedia ZnodeMedia { get; set; }
        public virtual ZnodePortalGlobalAttributeValue ZnodePortalGlobalAttributeValue { get; set; }
    }
}
