//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeStockNotice : ZnodeEntityBaseModel
    {
        public int StockNoticeId { get; set; }
        public string ParentSKU { get; set; }
        public string SKU { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int PortalId { get; set; }
        public int CatalogId { get; set; }
        public bool IsEmailSent { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
