//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeGoogleTagManager : ZnodeEntityBaseModel
    {
        public int GoogleTagManagerId { get; set; }
        public int PortalId { get; set; }
        public bool IsActive { get; set; }
        public string ContainerId { get; set; }
        public string AnalyticsIdForAddToCart { get; set; }
        public string AnalyticsIdForRemoveFromCart { get; set; }
        public string AnalyticsUId { get; set; }
        public Nullable<bool> AnalyticsIsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool EnableEnhancedEcommerce { get; set; }
    
        public virtual ZnodePortal ZnodePortal { get; set; }
    }
}
