//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeMediaAttributeValue : ZnodeEntityBaseModel
    {
        public int MediaAttributeValueId { get; set; }
        public Nullable<int> MediaCategoryId { get; set; }
        public Nullable<int> MediaAttributeId { get; set; }
        public Nullable<int> MediaAttributeDefaultValueId { get; set; }
        public string AttributeValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeMediaAttribute ZnodeMediaAttribute { get; set; }
        public virtual ZnodeMediaAttributeDefaultValue ZnodeMediaAttributeDefaultValue { get; set; }
        public virtual ZnodeMediaCategory ZnodeMediaCategory { get; set; }
    }
}
