//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishVersionEntity : ZnodeEntityBaseModel
    {
        public int PublishVersionEntityId { get; set; }
        public int ZnodeCatalogId { get; set; }
        public string RevisionType { get; set; }
        public int LocaleId { get; set; }
        public bool IsPublishSuccess { get; set; }
        public int VersionId { get; set; }
    }
}
