//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeRmaRequest : ZnodeEntityBaseModel
    {
        public ZnodeRmaRequest()
        {
            this.ZnodeRmaRequestItems = new HashSet<ZnodeRmaRequestItem>();
        }
    
        public int RmaRequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RmaRequestStatusId { get; set; }
        public string RequestNumber { get; set; }
        public Nullable<decimal> TaxCost { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeRmaRequestStatu ZnodeRmaRequestStatu { get; set; }
        public virtual ICollection<ZnodeRmaRequestItem> ZnodeRmaRequestItems { get; set; }
    }
}
