//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeAttributeInputValidationRule : ZnodeEntityBaseModel
    {
        public ZnodeAttributeInputValidationRule()
        {
            this.ZnodeGlobalAttributeValidations = new HashSet<ZnodeGlobalAttributeValidation>();
            this.ZnodeMediaAttributeValidations = new HashSet<ZnodeMediaAttributeValidation>();
            this.ZnodeMediaAttributeValidations1 = new HashSet<ZnodeMediaAttributeValidation>();
            this.ZnodePimAttributeValidations = new HashSet<ZnodePimAttributeValidation>();
            this.ZnodePromotionAttributeValidations = new HashSet<ZnodePromotionAttributeValidation>();
        }
    
        public int InputValidationRuleId { get; set; }
        public Nullable<int> InputValidationId { get; set; }
        public string ValidationRule { get; set; }
        public string ValidationName { get; set; }
        public int DisplayOrder { get; set; }
        public string RegExp { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeAttributeInputValidation ZnodeAttributeInputValidation { get; set; }
        public virtual ICollection<ZnodeGlobalAttributeValidation> ZnodeGlobalAttributeValidations { get; set; }
        public virtual ICollection<ZnodeMediaAttributeValidation> ZnodeMediaAttributeValidations { get; set; }
        public virtual ICollection<ZnodeMediaAttributeValidation> ZnodeMediaAttributeValidations1 { get; set; }
        public virtual ICollection<ZnodePimAttributeValidation> ZnodePimAttributeValidations { get; set; }
        public virtual ICollection<ZnodePromotionAttributeValidation> ZnodePromotionAttributeValidations { get; set; }
    }
}
