//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishContentPageConfigEntity : ZnodeEntityBaseModel
    {
        public int PublishContentPageConfigEntityId { get; set; }
        public int VersionId { get; set; }
        public Nullable<System.DateTime> PublishStartTime { get; set; }
        public int ContentPageId { get; set; }
        public int PortalId { get; set; }
        public string FileName { get; set; }
        public string ProfileId { get; set; }
        public int LocaleId { get; set; }
        public string PageTitle { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool IsActive { get; set; }
    }
}
