//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePromotionType : ZnodeEntityBaseModel
    {
        public ZnodePromotionType()
        {
            this.ZnodePromotions = new HashSet<ZnodePromotion>();
            this.ZnodeOmsOrderDiscounts = new HashSet<ZnodeOmsOrderDiscount>();
            this.ZnodeOmsQuoteOrderDiscounts = new HashSet<ZnodeOmsQuoteOrderDiscount>();
            this.ZnodeImportTemplates = new HashSet<ZnodeImportTemplate>();
        }
    
        public int PromotionTypeId { get; set; }
        public string ClassType { get; set; }
        public string ClassName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodePromotion> ZnodePromotions { get; set; }
        public virtual ICollection<ZnodeOmsOrderDiscount> ZnodeOmsOrderDiscounts { get; set; }
        public virtual ICollection<ZnodeOmsQuoteOrderDiscount> ZnodeOmsQuoteOrderDiscounts { get; set; }
        public virtual ICollection<ZnodeImportTemplate> ZnodeImportTemplates { get; set; }
    }
}
