//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeECertificateWallet : ZnodeEntityBaseModel
    {
        public int ECertificateWalletId { get; set; }
        public Nullable<int> ECertificateId { get; set; }
        public Nullable<int> IssuedByUserId { get; set; }
        public Nullable<int> IssuedToUserId { get; set; }
        public decimal BalanceAmount { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeECertificate ZnodeECertificate { get; set; }
        public virtual ZnodeUser ZnodeUser { get; set; }
        public virtual ZnodeUser ZnodeUser1 { get; set; }
    }
}
