//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePortalPaymentGroup : ZnodeEntityBaseModel
    {
        public ZnodePortalPaymentGroup()
        {
            this.ZnodePortalPaymentApprovers = new HashSet<ZnodePortalPaymentApprover>();
            this.ZnodeUserApprovers = new HashSet<ZnodeUserApprover>();
        }
    
        public int PortalPaymentGroupId { get; set; }
        public string PaymentGroupCode { get; set; }
        public int PortalApprovalId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ZnodePortalApproval ZnodePortalApproval { get; set; }
        public virtual ICollection<ZnodePortalPaymentApprover> ZnodePortalPaymentApprovers { get; set; }
        public virtual ICollection<ZnodeUserApprover> ZnodeUserApprovers { get; set; }
    }
}
