//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeListViewFilter : ZnodeEntityBaseModel
    {
        public int ListViewFilterId { get; set; }
        public Nullable<int> ListViewId { get; set; }
        public string FilterName { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeListView ZnodeListView { get; set; }
    }
}
