//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePriceTier : ZnodeEntityBaseModel
    {
        public int PriceTierId { get; set; }
        public Nullable<int> PriceListId { get; set; }
        public string SKU { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<int> UomId { get; set; }
        public Nullable<decimal> UnitSize { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
    
        public virtual ZnodeUom ZnodeUom { get; set; }
        public virtual ZnodePriceList ZnodePriceList { get; set; }
    }
}
