//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishPortalBrandEntity : ZnodeEntityBaseModel
    {
        public int PublishPortalBrandEntityId { get; set; }
        public int VersionId { get; set; }
        public Nullable<System.DateTime> PublishStartTime { get; set; }
        public Nullable<int> PortalId { get; set; }
        public int LocaleId { get; set; }
        public int BrandId { get; set; }
        public string BrandCode { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> MediaId { get; set; }
        public string WebsiteLink { get; set; }
        public string Description { get; set; }
        public string PublishState { get; set; }
        public string SEOTitle { get; set; }
        public string SEOKeywords { get; set; }
        public string SEODescription { get; set; }
        public string SEOFriendlyPageName { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public string MediaPath { get; set; }
        public Nullable<int> CMSSEODetailId { get; set; }
        public Nullable<int> CMSSEODetailLocaleId { get; set; }
        public int BrandDetailLocaleId { get; set; }
        public string ImageName { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
    }
}
