//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeMultifront : ZnodeEntityBaseModel
    {
        public int MultifrontId { get; set; }
        public string VersionName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> MajorVersion { get; set; }
        public Nullable<int> MinorVersion { get; set; }
        public Nullable<int> LowerVersion { get; set; }
        public Nullable<int> BuildVersion { get; set; }
        public Nullable<int> PatchIndex { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
