//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePortalShippingDetail : ZnodeEntityBaseModel
    {
        public int PortalShippingDetailId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string ShippingOriginZipCode { get; set; }
        public Nullable<int> ShopByPriceMin { get; set; }
        public Nullable<int> ShopByPriceMax { get; set; }
        public Nullable<int> ShopByPriceIncrement { get; set; }
        public string FedExClientProductId { get; set; }
        public string FedExClientProductVersion { get; set; }
        public string FedExDropoffType { get; set; }
        public string FedExPackagingType { get; set; }
        public string ShippingOriginStateCode { get; set; }
        public string ShippingOriginCountryCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodePortal ZnodePortal { get; set; }
    }
}
