//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeTimeZone : ZnodeEntityBaseModel
    {
        public int TimeZoneId { get; set; }
        public string TimeZoneDetailsCode { get; set; }
        public string TimeZoneDetailsDesc { get; set; }
        public int DifferenceInSeconds { get; set; }
        public string DaylightBeginsAt { get; set; }
        public string DaylightEndsAt { get; set; }
        public Nullable<int> DSTInSeconds { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
