//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishConfigurableProductEntity : ZnodeEntityBaseModel
    {
        public int PublishConfigurableProductEntityId { get; set; }
        public int VersionId { get; set; }
        public int ZnodeProductId { get; set; }
        public int ZnodeCatalogId { get; set; }
        public int AssociatedZnodeProductId { get; set; }
        public int AssociatedProductDisplayOrder { get; set; }
        public string SelectValues { get; set; }
        public string ConfigurableAttributeCodes { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
