//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeInventory : ZnodeEntityBaseModel
    {
        public int InventoryId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string SKU { get; set; }
        public decimal Quantity { get; set; }
        public decimal ReOrderLevel { get; set; }
        public string ExternalId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public decimal BackOrderQuantity { get; set; }
        public Nullable<System.DateTime> BackOrderExpectedDate { get; set; }
    
        public virtual ZnodeWarehouse ZnodeWarehouse { get; set; }
    }
}
