//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCaseType : ZnodeEntityBaseModel
    {
        public ZnodeCaseType()
        {
            this.ZnodeCaseRequests = new HashSet<ZnodeCaseRequest>();
        }
    
        public int CaseTypeId { get; set; }
        public string CaseTypeName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeCaseRequest> ZnodeCaseRequests { get; set; }
    }
}
