//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsQuoteTaxOrderDetail : ZnodeEntityBaseModel
    {
        public int OmsQuoteTaxOrderDetailsId { get; set; }
        public int OmsQuoteId { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> PST { get; set; }
        public Nullable<decimal> HST { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<decimal> ImportDuty { get; set; }
    
        public virtual ZnodeOmsQuote ZnodeOmsQuote { get; set; }
    }
}
