//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCMSContentPageGroup : ZnodeEntityBaseModel
    {
        public ZnodeCMSContentPageGroup()
        {
            this.ZnodeCMSContentPageGroup1 = new HashSet<ZnodeCMSContentPageGroup>();
            this.ZnodeCMSContentPageGroupLocales = new HashSet<ZnodeCMSContentPageGroupLocale>();
            this.ZnodeCMSContentPageGroupMappings = new HashSet<ZnodeCMSContentPageGroupMapping>();
        }
    
        public int CMSContentPageGroupId { get; set; }
        public Nullable<int> ParentCMSContentPageGroupId { get; set; }
        public string Code { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeCMSContentPageGroup> ZnodeCMSContentPageGroup1 { get; set; }
        public virtual ZnodeCMSContentPageGroup ZnodeCMSContentPageGroup2 { get; set; }
        public virtual ICollection<ZnodeCMSContentPageGroupLocale> ZnodeCMSContentPageGroupLocales { get; set; }
        public virtual ICollection<ZnodeCMSContentPageGroupMapping> ZnodeCMSContentPageGroupMappings { get; set; }
    }
}
