//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsOrderDetail : ZnodeEntityBaseModel
    {
        public ZnodeOmsOrderDetail()
        {
            this.ZnodeGiftCardHistories = new HashSet<ZnodeGiftCardHistory>();
            this.ZnodeOmsCustomerShippings = new HashSet<ZnodeOmsCustomerShipping>();
            this.ZnodeOmsEmailHistories = new HashSet<ZnodeOmsEmailHistory>();
            this.ZnodeOmsHistories = new HashSet<ZnodeOmsHistory>();
            this.ZnodeOmsNotes = new HashSet<ZnodeOmsNote>();
            this.ZnodeOmsOrderLineItems = new HashSet<ZnodeOmsOrderLineItem>();
            this.ZnodeOmsOrderWarehouses = new HashSet<ZnodeOmsOrderWarehouse>();
            this.ZnodeOmsPaymentRefunds = new HashSet<ZnodeOmsPaymentRefund>();
            this.ZnodeOmsReferralCommissions = new HashSet<ZnodeOmsReferralCommission>();
            this.ZnodeOmsTaxOrderDetails = new HashSet<ZnodeOmsTaxOrderDetail>();
            this.ZnodeOmsOrderDiscounts = new HashSet<ZnodeOmsOrderDiscount>();
            this.ZnodeRmaReturnDetails = new HashSet<ZnodeRmaReturnDetail>();
            this.ZnodeOmsTaxOrderSummaries = new HashSet<ZnodeOmsTaxOrderSummary>();
        }
    
        public int OmsOrderDetailsId { get; set; }
        public int OmsOrderId { get; set; }
        public int PortalId { get; set; }
        public int UserId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OmsOrderStateId { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string BillingFirstName { get; set; }
        public string BillingLastName { get; set; }
        public string BillingCompanyName { get; set; }
        public string BillingStreet1 { get; set; }
        public string BillingStreet2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingStateCode { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPhoneNumber { get; set; }
        public string BillingEmailId { get; set; }
        public Nullable<decimal> TaxCost { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> OverDueAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ShippingNumber { get; set; }
        public string TrackingNumber { get; set; }
        public string CouponCode { get; set; }
        public string PromoDescription { get; set; }
        public Nullable<int> ReferralUserId { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<int> OmsPaymentStateId { get; set; }
        public Nullable<System.DateTime> WebServiceDownloadDate { get; set; }
        public Nullable<int> PaymentSettingId { get; set; }
        public string PaymentTransactionToken { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PoDocument { get; set; }
        public bool IsActive { get; set; }
        public string ExternalId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreditCardNumber { get; set; }
        public Nullable<bool> IsShippingCostEdited { get; set; }
        public Nullable<bool> IsTaxCostEdited { get; set; }
        public Nullable<decimal> ShippingDifference { get; set; }
        public Nullable<decimal> EstimateShippingCost { get; set; }
        public string TransactionId { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CardType { get; set; }
        public Nullable<int> CreditCardExpMonth { get; set; }
        public Nullable<int> CreditCardExpYear { get; set; }
        public Nullable<decimal> TotalAdditionalCost { get; set; }
        public string PaymentDisplayName { get; set; }
        public string PaymentExternalId { get; set; }
        public string CultureCode { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> InHandDate { get; set; }
        public string IpAddress { get; set; }
        public string JobName { get; set; }
        public string ShippingConstraintCode { get; set; }
        public Nullable<decimal> ShippingDiscount { get; set; }
        public Nullable<decimal> ShippingHandlingCharges { get; set; }
        public Nullable<decimal> ReturnCharges { get; set; }
        public Nullable<bool> IsCalculateTaxAfterDiscount { get; set; }

        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<decimal> OrderTotalWithoutVoucher { get; set; }
        public Nullable<decimal> ImportDuty { get; set; }
        public Nullable<bool> IsPricesInclusiveOfTaxes { get; set; }
        public Nullable<decimal> RemainingOrderAmount { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual ICollection<ZnodeGiftCardHistory> ZnodeGiftCardHistories { get; set; }
        public virtual ICollection<ZnodeOmsCustomerShipping> ZnodeOmsCustomerShippings { get; set; }
        public virtual ICollection<ZnodeOmsEmailHistory> ZnodeOmsEmailHistories { get; set; }
        public virtual ICollection<ZnodeOmsHistory> ZnodeOmsHistories { get; set; }
        public virtual ICollection<ZnodeOmsNote> ZnodeOmsNotes { get; set; }
        public virtual ZnodeOmsOrder ZnodeOmsOrder { get; set; }
        public virtual ZnodeOmsOrderState ZnodeOmsOrderState { get; set; }
        public virtual ZnodeOmsPaymentState ZnodeOmsPaymentState { get; set; }
        public virtual ZnodeOmsPaymentState ZnodeOmsPaymentState1 { get; set; }
        public virtual ZnodePaymentSetting ZnodePaymentSetting { get; set; }
        public virtual ZnodePaymentType ZnodePaymentType { get; set; }
        public virtual ZnodeShipping ZnodeShipping { get; set; }
        public virtual ZnodeUser ZnodeUser { get; set; }
        public virtual ICollection<ZnodeOmsOrderLineItem> ZnodeOmsOrderLineItems { get; set; }
        public virtual ICollection<ZnodeOmsOrderWarehouse> ZnodeOmsOrderWarehouses { get; set; }
        public virtual ICollection<ZnodeOmsPaymentRefund> ZnodeOmsPaymentRefunds { get; set; }
        public virtual ICollection<ZnodeOmsReferralCommission> ZnodeOmsReferralCommissions { get; set; }
        public virtual ICollection<ZnodeOmsTaxOrderDetail> ZnodeOmsTaxOrderDetails { get; set; }
        public virtual ZnodeAddress ZnodeAddress { get; set; }
        public virtual ICollection<ZnodeOmsOrderDiscount> ZnodeOmsOrderDiscounts { get; set; }
        public virtual ICollection<ZnodeRmaReturnDetail> ZnodeRmaReturnDetails { get; set; }
        public virtual ICollection<ZnodeOmsTaxOrderSummary> ZnodeOmsTaxOrderSummaries { get; set; }
    }
}
