//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsCustomerShipping : ZnodeEntityBaseModel
    {
        public int OmsCustomerShippingId { get; set; }
        public Nullable<int> OmsOrderDetailsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ShippingTypeId { get; set; }
        public string AccountNumber { get; set; }
        public string ShippingMethod { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeShippingType ZnodeShippingType { get; set; }
        public virtual ZnodeUser ZnodeUser { get; set; }
        public virtual ZnodeOmsOrderDetail ZnodeOmsOrderDetail { get; set; }
    }
}
