//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePimCategory : ZnodeEntityBaseModel
    {
        public ZnodePimCategory()
        {
            this.ZnodePimCategoryHierarchies = new HashSet<ZnodePimCategoryHierarchy>();
            this.ZnodePimCategoryProducts = new HashSet<ZnodePimCategoryProduct>();
            this.ZnodePimCategoryAttributeValues = new HashSet<ZnodePimCategoryAttributeValue>();
        }
    
        public int PimCategoryId { get; set; }
        public Nullable<int> PimAttributeFamilyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ExternalId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<byte> IsCategoryPublish { get; set; }
        public Nullable<byte> PublishStateId { get; set; }
    
        public virtual ZnodePimAttributeFamily ZnodePimAttributeFamily { get; set; }
        public virtual ZnodePimCategory ZnodePimCategory1 { get; set; }
        public virtual ZnodePimCategory ZnodePimCategory2 { get; set; }
        public virtual ZnodePimCategory ZnodePimCategory11 { get; set; }
        public virtual ZnodePimCategory ZnodePimCategory3 { get; set; }
        public virtual ZnodePublishState ZnodePublishState { get; set; }
        public virtual ICollection<ZnodePimCategoryHierarchy> ZnodePimCategoryHierarchies { get; set; }
        public virtual ICollection<ZnodePimCategoryProduct> ZnodePimCategoryProducts { get; set; }
        public virtual ICollection<ZnodePimCategoryAttributeValue> ZnodePimCategoryAttributeValues { get; set; }
    }
}
