//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeProfilePaymentSetting : ZnodeEntityBaseModel
    {
        public int ProfilePaymentSettingId { get; set; }
        public Nullable<int> PaymentSettingId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<byte> PublishStateId { get; set; }
    
        public virtual ZnodePaymentSetting ZnodePaymentSetting { get; set; }
        public virtual ZnodeProfile ZnodeProfile { get; set; }
        public virtual ZnodePublishState ZnodePublishState { get; set; }
    }
}
