//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeUserApprover : ZnodeEntityBaseModel
    {
        public int UserApproverId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApproverLevelId { get; set; }
        public int ApproverUserId { get; set; }
        public int ApproverOrder { get; set; }
        public bool IsNotifyEmail { get; set; }
        public bool IsMandatory { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public decimal FromBudgetAmount { get; set; }
        public Nullable<decimal> ToBudgetAmount { get; set; }
        public Nullable<bool> IsNoLimit { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> PortalApprovalId { get; set; }
        public Nullable<int> PortalPaymentGroupId { get; set; }
    
        public virtual ZnodeApproverLevel ZnodeApproverLevel { get; set; }
        public virtual ZnodePortalApproval ZnodePortalApproval { get; set; }
        public virtual ZnodePortalPaymentGroup ZnodePortalPaymentGroup { get; set; }
        public virtual ZnodeUser ZnodeUser { get; set; }
        public virtual ZnodeUser ZnodeUser1 { get; set; }
    }
}
