//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePimVendor : ZnodeEntityBaseModel
    {
        public int PimVendorId { get; set; }
        public string VendorCode { get; set; }
        public Nullable<int> PimAttributeId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string ExternalVendorNo { get; set; }
        public string Email { get; set; }
        public string NotificationEmailID { get; set; }
        public string EmailNotificationTemplate { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodePimAttribute ZnodePimAttribute { get; set; }
        public virtual ZnodeAddress ZnodeAddress { get; set; }
    }
}
