//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCMSWidget : ZnodeEntityBaseModel
    {
        public ZnodeCMSWidget()
        {
            this.ZnodeCMSFormWidgetConfigurations = new HashSet<ZnodeCMSFormWidgetConfiguration>();
            this.ZnodeCMSTextWidgetConfigurations = new HashSet<ZnodeCMSTextWidgetConfiguration>();
            this.ZnodeCMSWidgetSliderBanners = new HashSet<ZnodeCMSWidgetSliderBanner>();
            this.ZnodeCMSWidgetSliderBanners1 = new HashSet<ZnodeCMSWidgetSliderBanner>();
            this.ZnodeCMSWidgetTitleConfigurations = new HashSet<ZnodeCMSWidgetTitleConfiguration>();
            this.ZnodeCMSWidgetBrands = new HashSet<ZnodeCMSWidgetBrand>();
            this.ZnodeCMSWidgetCategories = new HashSet<ZnodeCMSWidgetCategory>();
            this.ZnodeCMSWidgetProducts = new HashSet<ZnodeCMSWidgetProduct>();
            this.ZnodeCMSMediaConfigurations = new HashSet<ZnodeCMSMediaConfiguration>();
            this.ZnodeCMSContainerConfigurations = new HashSet<ZnodeCMSContainerConfiguration>();
        }
    
        public int CMSWidgetsId { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public bool IsConfigurable { get; set; }
        public string FileName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeCMSFormWidgetConfiguration> ZnodeCMSFormWidgetConfigurations { get; set; }
        public virtual ICollection<ZnodeCMSTextWidgetConfiguration> ZnodeCMSTextWidgetConfigurations { get; set; }
        public virtual ICollection<ZnodeCMSWidgetSliderBanner> ZnodeCMSWidgetSliderBanners { get; set; }
        public virtual ICollection<ZnodeCMSWidgetSliderBanner> ZnodeCMSWidgetSliderBanners1 { get; set; }
        public virtual ICollection<ZnodeCMSWidgetTitleConfiguration> ZnodeCMSWidgetTitleConfigurations { get; set; }
        public virtual ICollection<ZnodeCMSWidgetBrand> ZnodeCMSWidgetBrands { get; set; }
        public virtual ICollection<ZnodeCMSWidgetCategory> ZnodeCMSWidgetCategories { get; set; }
        public virtual ICollection<ZnodeCMSWidgetProduct> ZnodeCMSWidgetProducts { get; set; }
        public virtual ICollection<ZnodeCMSMediaConfiguration> ZnodeCMSMediaConfigurations { get; set; }
        public virtual ICollection<ZnodeCMSContainerConfiguration> ZnodeCMSContainerConfigurations { get; set; }
    }
}
