//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeSortSetting : ZnodeEntityBaseModel
    {
        public ZnodeSortSetting()
        {
            this.ZnodePortalSortSettings = new HashSet<ZnodePortalSortSetting>();
        }
    
        public int SortSettingId { get; set; }
        public string SortName { get; set; }
        public int SortValue { get; set; }
        public int DisplayOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodePortalSortSetting> ZnodePortalSortSettings { get; set; }
    }
}
