//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeShippingRule : ZnodeEntityBaseModel
    {
        public ZnodeShippingRule()
        {
            this.ZnodeShippingSKUs = new HashSet<ZnodeShippingSKU>();
        }
    
        public int ShippingRuleId { get; set; }
        public int ShippingId { get; set; }
        public string ShippingRuleTypeCode { get; set; }
        public string ClassName { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public decimal BaseCost { get; set; }
        public decimal PerItemCost { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string ExternalId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeShipping ZnodeShipping { get; set; }
        public virtual ICollection<ZnodeShippingSKU> ZnodeShippingSKUs { get; set; }
    }
}
