//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCMSSliderBanner : ZnodeEntityBaseModel
    {
        public ZnodeCMSSliderBanner()
        {
            this.ZnodeCMSSliderBannerLocales = new HashSet<ZnodeCMSSliderBannerLocale>();
        }
    
        public int CMSSliderBannerId { get; set; }
        public int CMSSliderId { get; set; }
        public string TextAlignment { get; set; }
        public Nullable<int> BannerSequence { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeCMSSlider ZnodeCMSSlider { get; set; }
        public virtual ICollection<ZnodeCMSSliderBannerLocale> ZnodeCMSSliderBannerLocales { get; set; }
    }
}
