//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeMediaAttribute : ZnodeEntityBaseModel
    {
        public ZnodeMediaAttribute()
        {
            this.ZnodeMediaAttribute1 = new HashSet<ZnodeMediaAttribute>();
            this.ZnodeMediaAttributeDefaultValues = new HashSet<ZnodeMediaAttributeDefaultValue>();
            this.ZnodeMediaAttributeGroupMappers = new HashSet<ZnodeMediaAttributeGroupMapper>();
            this.ZnodeMediaAttributeLocales = new HashSet<ZnodeMediaAttributeLocale>();
            this.ZnodeMediaAttributeValidations = new HashSet<ZnodeMediaAttributeValidation>();
            this.ZnodeMediaAttributeValues = new HashSet<ZnodeMediaAttributeValue>();
            this.ZnodeMediaFamilyGroupMappers = new HashSet<ZnodeMediaFamilyGroupMapper>();
        }
    
        public int MediaAttributeId { get; set; }
        public Nullable<int> ParentMediaAttributeId { get; set; }
        public Nullable<int> AttributeTypeId { get; set; }
        public string AttributeCode { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> IsLocalizable { get; set; }
        public Nullable<bool> IsFilterable { get; set; }
        public bool IsSystemDefined { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string HelpDescription { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ZnodeAttributeType ZnodeAttributeType { get; set; }
        public virtual ICollection<ZnodeMediaAttribute> ZnodeMediaAttribute1 { get; set; }
        public virtual ZnodeMediaAttribute ZnodeMediaAttribute2 { get; set; }
        public virtual ICollection<ZnodeMediaAttributeDefaultValue> ZnodeMediaAttributeDefaultValues { get; set; }
        public virtual ICollection<ZnodeMediaAttributeGroupMapper> ZnodeMediaAttributeGroupMappers { get; set; }
        public virtual ICollection<ZnodeMediaAttributeLocale> ZnodeMediaAttributeLocales { get; set; }
        public virtual ICollection<ZnodeMediaAttributeValidation> ZnodeMediaAttributeValidations { get; set; }
        public virtual ICollection<ZnodeMediaAttributeValue> ZnodeMediaAttributeValues { get; set; }
        public virtual ICollection<ZnodeMediaFamilyGroupMapper> ZnodeMediaFamilyGroupMappers { get; set; }
    }
}
