//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCurrency : ZnodeEntityBaseModel
    {
        public ZnodeCurrency()
        {
            this.ZnodePortalUnits = new HashSet<ZnodePortalUnit>();
            this.ZnodeShippings = new HashSet<ZnodeShipping>();
            this.ZnodeCultures = new HashSet<ZnodeCulture>();
            this.ZnodePriceLists = new HashSet<ZnodePriceList>();
        }
    
        public int CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencySuffix { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public string Symbol { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodePortalUnit> ZnodePortalUnits { get; set; }
        public virtual ICollection<ZnodeShipping> ZnodeShippings { get; set; }
        public virtual ICollection<ZnodeCulture> ZnodeCultures { get; set; }
        public virtual ICollection<ZnodePriceList> ZnodePriceLists { get; set; }
    }
}
