//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsOrderShipment : ZnodeEntityBaseModel
    {
        public ZnodeOmsOrderShipment()
        {
            this.ZnodeOmsOrderLineItems = new HashSet<ZnodeOmsOrderLineItem>();
        }
    
        public int OmsOrderShipmentId { get; set; }
        public string ShipName { get; set; }
        public string ShipToFirstName { get; set; }
        public string ShipToLastName { get; set; }
        public string ShipToCompanyName { get; set; }
        public string ShipToStreet1 { get; set; }
        public string ShipToStreet2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToStateCode { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToPhoneNumber { get; set; }
        public string ShipToEmailId { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<ZnodeOmsOrderLineItem> ZnodeOmsOrderLineItems { get; set; }
        public virtual ZnodeShipping ZnodeShipping { get; set; }
        public virtual ZnodeAddress ZnodeAddress { get; set; }
    }
}
