//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishWidgetSliderBannerEntity : ZnodeEntityBaseModel
    {
        public int PublishWidgetSliderBannerEntityId { get; set; }
        public int VersionId { get; set; }
        public Nullable<System.DateTime> PublishStartTime { get; set; }
        public int WidgetSliderBannerId { get; set; }
        public int MappingId { get; set; }
        public int PortalId { get; set; }
        public int LocaleId { get; set; }
        public string Type { get; set; }
        public string Navigation { get; set; }
        public bool AutoPlay { get; set; }
        public Nullable<int> AutoplayTimeOut { get; set; }
        public bool AutoplayHoverPause { get; set; }
        public string TransactionStyle { get; set; }
        public string WidgetsKey { get; set; }
        public string TypeOFMapping { get; set; }
        public int SliderId { get; set; }
        public string SliderBanners { get; set; }
    }
}
