//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOmsQuoteType : ZnodeEntityBaseModel
    {
        public ZnodeOmsQuoteType()
        {
            this.ZnodeOmsQuotes = new HashSet<ZnodeOmsQuote>();
        }
    
        public int OmsQuoteTypeId { get; set; }
        public string QuoteTypeName { get; set; }
        public string QuoteTypeCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeOmsQuote> ZnodeOmsQuotes { get; set; }
    }
}
