//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeCMSContainerProfileVariantLocale : ZnodeEntityBaseModel
    {
        public int CMSContainerProfileVariantLocaleId { get; set; }
        public int CMSContainerProfileVariantId { get; set; }
        public Nullable<int> CMSContainerTemplateId { get; set; }
        public int LocaleId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ZnodeCMSContainerProfileVariant ZnodeCMSContainerProfileVariant { get; set; }
        public virtual ZnodeLocale ZnodeLocale { get; set; }
        public virtual ZnodeCMSContainerTemplate ZnodeCMSContainerTemplate { get; set; }
    }
}
