//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePublishCatalogLog : ZnodeEntityBaseModel
    {
        public int PublishCatalogLogId { get; set; }
        public Nullable<int> PublishCatalogId { get; set; }
        public int PimCatalogId { get; set; }
        public Nullable<bool> IsCatalogPublished { get; set; }
        public string PublishCategoryId { get; set; }
        public Nullable<bool> IsCategoryPublished { get; set; }
        public string PublishProductId { get; set; }
        public Nullable<bool> IsProductPublished { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Token { get; set; }
        public Nullable<int> LocaleId { get; set; }
        public Nullable<byte> PublishStateId { get; set; }
    
        public virtual ZnodePublishState ZnodePublishState { get; set; }
        public virtual ZnodeUser ZnodeUser { get; set; }
    }
}
