//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodePimAttributeFamily : ZnodeEntityBaseModel
    {
        public ZnodePimAttributeFamily()
        {
            this.ZnodeImportTemplates = new HashSet<ZnodeImportTemplate>();
            this.ZnodePimAttributeValues = new HashSet<ZnodePimAttributeValue>();
            this.ZnodePimCategories = new HashSet<ZnodePimCategory>();
            this.ZnodePimCategoryAttributeValues = new HashSet<ZnodePimCategoryAttributeValue>();
            this.ZnodePimFamilyGroupMappers = new HashSet<ZnodePimFamilyGroupMapper>();
            this.ZnodePimFamilyLocales = new HashSet<ZnodePimFamilyLocale>();
            this.ZnodePimProducts = new HashSet<ZnodePimProduct>();
        }
    
        public int PimAttributeFamilyId { get; set; }
        public string FamilyCode { get; set; }
        public bool IsSystemDefined { get; set; }
        public bool IsDefaultFamily { get; set; }
        public bool IsCategory { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<ZnodeImportTemplate> ZnodeImportTemplates { get; set; }
        public virtual ICollection<ZnodePimAttributeValue> ZnodePimAttributeValues { get; set; }
        public virtual ICollection<ZnodePimCategory> ZnodePimCategories { get; set; }
        public virtual ICollection<ZnodePimCategoryAttributeValue> ZnodePimCategoryAttributeValues { get; set; }
        public virtual ICollection<ZnodePimFamilyGroupMapper> ZnodePimFamilyGroupMappers { get; set; }
        public virtual ICollection<ZnodePimFamilyLocale> ZnodePimFamilyLocales { get; set; }
        public virtual ICollection<ZnodePimProduct> ZnodePimProducts { get; set; }
    }
}
