//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeProductFeed : ZnodeEntityBaseModel
    {
        public int ProductFeedId { get; set; }
        public int LocaleId { get; set; }
        public int ProductFeedSiteMapTypeId { get; set; }
        public int ProductFeedTypeId { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int PortalId { get; set; }
        public int FileCount { get; set; }
    
        public virtual ZnodeLocale ZnodeLocale { get; set; }
        public virtual ZnodePortal ZnodePortal { get; set; }
        public virtual ZnodeProductFeedSiteMapType ZnodeProductFeedSiteMapType { get; set; }
        public virtual ZnodeProductFeedType ZnodeProductFeedType { get; set; }
    }
}
