//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeOrderPayment : ZnodeEntityBaseModel
    {
        public int OrderPaymentId { get; set; }
        public Nullable<int> OmsOrderId { get; set; }
        public string TransactionReference { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> PaymentGatewayId { get; set; }
    
        public virtual ZnodeOmsOrder ZnodeOmsOrder { get; set; }
        public virtual ZnodePaymentGateway ZnodePaymentGateway { get; set; }
    }
}
