//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeMediaConfiguration : ZnodeEntityBaseModel
    {
        public ZnodeMediaConfiguration()
        {
            this.ZnodeMedias = new HashSet<ZnodeMedia>();
        }
    
        public int MediaConfigurationId { get; set; }
        public Nullable<int> MediaServerMasterId { get; set; }
        public string Server { get; set; }
        public string AccessKey { get; set; }
        public string SecretKey { get; set; }
        public string URL { get; set; }
        public string BucketName { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CDNUrl { get; set; }
    
        public virtual ICollection<ZnodeMedia> ZnodeMedias { get; set; }
        public virtual ZnodeMediaServerMaster ZnodeMediaServerMaster { get; set; }
    }
}
