//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeUser : ZnodeEntityBaseModel
    {
        public ZnodeUser()
        {
            this.ZnodeAccountUserOrderApprovals = new HashSet<ZnodeAccountUserOrderApproval>();
            this.ZnodeAccountUserOrderApprovals1 = new HashSet<ZnodeAccountUserOrderApproval>();
            this.ZnodeAccountUserPermissions = new HashSet<ZnodeAccountUserPermission>();
            this.ZnodeBlogNewsComments = new HashSet<ZnodeBlogNewsComment>();
            this.ZnodeCaseRequests = new HashSet<ZnodeCaseRequest>();
            this.ZnodeCaseRequests1 = new HashSet<ZnodeCaseRequest>();
            this.ZnodeCMSCustomerReviews = new HashSet<ZnodeCMSCustomerReview>();
            this.ZnodeDepartmentUsers = new HashSet<ZnodeDepartmentUser>();
            this.ZnodeECertificateWallets = new HashSet<ZnodeECertificateWallet>();
            this.ZnodeECertificateWallets1 = new HashSet<ZnodeECertificateWallet>();
            this.ZnodeFormBuilderSubmits = new HashSet<ZnodeFormBuilderSubmit>();
            this.ZnodeGiftCards = new HashSet<ZnodeGiftCard>();
            this.ZnodeMediaFolderUsers = new HashSet<ZnodeMediaFolderUser>();
            this.ZnodeNotes = new HashSet<ZnodeNote>();
            this.ZnodeOmsCookieMappings = new HashSet<ZnodeOmsCookieMapping>();
            this.ZnodeOmsCustomerShippings = new HashSet<ZnodeOmsCustomerShipping>();
            this.ZnodeOmsQuotes = new HashSet<ZnodeOmsQuote>();
            this.ZnodeOMSQuoteApprovals = new HashSet<ZnodeOMSQuoteApproval>();
            this.ZnodeOMSQuoteApprovals1 = new HashSet<ZnodeOMSQuoteApproval>();
            this.ZnodeOmsReferralCommissions = new HashSet<ZnodeOmsReferralCommission>();
            this.ZnodeOmsTemplates = new HashSet<ZnodeOmsTemplate>();
            this.ZnodeOmsUsersReferralUrls = new HashSet<ZnodeOmsUsersReferralUrl>();
            this.ZnodePriceListUsers = new HashSet<ZnodePriceListUser>();
            this.ZnodePublishCatalogLogs = new HashSet<ZnodePublishCatalogLog>();
            this.ZnodeUserAddresses = new HashSet<ZnodeUserAddress>();
            this.ZnodeUserApprovers = new HashSet<ZnodeUserApprover>();
            this.ZnodeUserApprovers1 = new HashSet<ZnodeUserApprover>();
            this.ZnodeUserPortals = new HashSet<ZnodeUserPortal>();
            this.ZnodeUserProfiles = new HashSet<ZnodeUserProfile>();
            this.ZnodeUserPromotions = new HashSet<ZnodeUserPromotion>();
            this.ZnodeUserWishLists = new HashSet<ZnodeUserWishList>();
            this.ZnodeSalesRepCustomerUserPortals = new HashSet<ZnodeSalesRepCustomerUserPortal>();
            this.ZnodeSalesRepCustomerUserPortals1 = new HashSet<ZnodeSalesRepCustomerUserPortal>();
            this.ZnodeSearchActivities = new HashSet<ZnodeSearchActivity>();
            this.ZnodeOmsOrderDetails = new HashSet<ZnodeOmsOrderDetail>();
            this.ZnodeRmaReturnDetails = new HashSet<ZnodeRmaReturnDetail>();
            this.ZnodeTradeCentricUsers = new HashSet<ZnodeTradeCentricUser>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string AspNetUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string CustomerPaymentGUID { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool EmailOptIn { get; set; }
        public string ReferralStatus { get; set; }
        public Nullable<decimal> ReferralCommission { get; set; }
        public Nullable<int> ReferralCommissionTypeId { get; set; }
        public bool IsActive { get; set; }
        public string ExternalId { get; set; }
        public Nullable<bool> IsShowMessage { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<int> MediaId { get; set; }
        public string UserVerificationType { get; set; }
        public string UserName { get; set; }
        public bool SMSOptIn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ZnodeAccount ZnodeAccount { get; set; }
        public virtual ICollection<ZnodeAccountUserOrderApproval> ZnodeAccountUserOrderApprovals { get; set; }
        public virtual ICollection<ZnodeAccountUserOrderApproval> ZnodeAccountUserOrderApprovals1 { get; set; }
        public virtual ICollection<ZnodeAccountUserPermission> ZnodeAccountUserPermissions { get; set; }
        public virtual ICollection<ZnodeBlogNewsComment> ZnodeBlogNewsComments { get; set; }
        public virtual ICollection<ZnodeCaseRequest> ZnodeCaseRequests { get; set; }
        public virtual ICollection<ZnodeCaseRequest> ZnodeCaseRequests1 { get; set; }
        public virtual ICollection<ZnodeCMSCustomerReview> ZnodeCMSCustomerReviews { get; set; }
        public virtual ICollection<ZnodeDepartmentUser> ZnodeDepartmentUsers { get; set; }
        public virtual ICollection<ZnodeECertificateWallet> ZnodeECertificateWallets { get; set; }
        public virtual ICollection<ZnodeECertificateWallet> ZnodeECertificateWallets1 { get; set; }
        public virtual ICollection<ZnodeFormBuilderSubmit> ZnodeFormBuilderSubmits { get; set; }
        public virtual ICollection<ZnodeGiftCard> ZnodeGiftCards { get; set; }
        public virtual ICollection<ZnodeMediaFolderUser> ZnodeMediaFolderUsers { get; set; }
        public virtual ICollection<ZnodeNote> ZnodeNotes { get; set; }
        public virtual ICollection<ZnodeOmsCookieMapping> ZnodeOmsCookieMappings { get; set; }
        public virtual ICollection<ZnodeOmsCustomerShipping> ZnodeOmsCustomerShippings { get; set; }
        public virtual ICollection<ZnodeOmsQuote> ZnodeOmsQuotes { get; set; }
        public virtual ICollection<ZnodeOMSQuoteApproval> ZnodeOMSQuoteApprovals { get; set; }
        public virtual ICollection<ZnodeOMSQuoteApproval> ZnodeOMSQuoteApprovals1 { get; set; }
        public virtual ICollection<ZnodeOmsReferralCommission> ZnodeOmsReferralCommissions { get; set; }
        public virtual ICollection<ZnodeOmsTemplate> ZnodeOmsTemplates { get; set; }
        public virtual ICollection<ZnodeOmsUsersReferralUrl> ZnodeOmsUsersReferralUrls { get; set; }
        public virtual ICollection<ZnodePriceListUser> ZnodePriceListUsers { get; set; }
        public virtual ICollection<ZnodePublishCatalogLog> ZnodePublishCatalogLogs { get; set; }
        public virtual ZnodeReferralCommissionType ZnodeReferralCommissionType { get; set; }
        public virtual ICollection<ZnodeUserAddress> ZnodeUserAddresses { get; set; }
        public virtual ICollection<ZnodeUserApprover> ZnodeUserApprovers { get; set; }
        public virtual ICollection<ZnodeUserApprover> ZnodeUserApprovers1 { get; set; }
        public virtual ICollection<ZnodeUserPortal> ZnodeUserPortals { get; set; }
        public virtual ICollection<ZnodeUserProfile> ZnodeUserProfiles { get; set; }
        public virtual ICollection<ZnodeUserPromotion> ZnodeUserPromotions { get; set; }
        public virtual ICollection<ZnodeUserWishList> ZnodeUserWishLists { get; set; }
        public virtual ICollection<ZnodeSalesRepCustomerUserPortal> ZnodeSalesRepCustomerUserPortals { get; set; }
        public virtual ICollection<ZnodeSalesRepCustomerUserPortal> ZnodeSalesRepCustomerUserPortals1 { get; set; }
        public virtual ICollection<ZnodeSearchActivity> ZnodeSearchActivities { get; set; }
        public virtual ICollection<ZnodeOmsOrderDetail> ZnodeOmsOrderDetails { get; set; }
        public virtual ICollection<ZnodeRmaReturnDetail> ZnodeRmaReturnDetails { get; set; }
        public virtual ICollection<ZnodeTradeCentricUser> ZnodeTradeCentricUsers { get; set; }
    }
}
