//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnodeBrandDetail : ZnodeEntityBaseModel
    {
        public ZnodeBrandDetail()
        {
            this.ZnodeBrandDetailLocales = new HashSet<ZnodeBrandDetailLocale>();
            this.ZnodeBrandPortals = new HashSet<ZnodeBrandPortal>();
            this.ZnodeBrandProducts = new HashSet<ZnodeBrandProduct>();
            this.ZnodePromotionBrands = new HashSet<ZnodePromotionBrand>();
            this.ZnodeCMSWidgetBrands = new HashSet<ZnodeCMSWidgetBrand>();
            this.ZnodePortalBrands = new HashSet<ZnodePortalBrand>();
        }
    
        public int BrandId { get; set; }
        public string BrandCode { get; set; }
        public Nullable<int> MediaId { get; set; }
        public string WebsiteLink { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
    
        public virtual ICollection<ZnodeBrandDetailLocale> ZnodeBrandDetailLocales { get; set; }
        public virtual ICollection<ZnodeBrandPortal> ZnodeBrandPortals { get; set; }
        public virtual ICollection<ZnodeBrandProduct> ZnodeBrandProducts { get; set; }
        public virtual ICollection<ZnodePromotionBrand> ZnodePromotionBrands { get; set; }
        public virtual ICollection<ZnodeCMSWidgetBrand> ZnodeCMSWidgetBrands { get; set; }
        public virtual ICollection<ZnodePortalBrand> ZnodePortalBrands { get; set; }
    }
}
