IF EXISTS (SELECT TOP 1 1 FROM SYSDATABASES WHERE Name = 'Znode_Multifront_90')
BEGIN 
	DECLARE @EEEE NVARCHAR(max)= 'USE [Znode_Multifront_90]'
	EXEC (@EEEE)
 PRINT '"Znode_Multifront_90" is already exists. ';
 SET NOEXEC ON;
END 
GO
USE [master]
GO
/****** Object:  Database [Znode_Multifront_90]    Script Date: 4/3/2017 8:34:00 PM ******/
CREATE DATABASE [Znode_Multifront_90]
GO
ALTER DATABASE [Znode_Multifront_90] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET ANSI_NULLS ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET ANSI_PADDING ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET ARITHABORT ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [Znode_Multifront_90] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [Znode_Multifront_90] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Znode_Multifront_90] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Znode_Multifront_90] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET RECOVERY FULL 
GO
ALTER DATABASE [Znode_Multifront_90] SET  MULTI_USER 
GO
ALTER DATABASE [Znode_Multifront_90] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [Znode_Multifront_90] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Znode_Multifront_90] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Znode_Multifront_90] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
CREATE TABLE Znode_Multifront_90..Znode_TempDBTable (Id INT  , CreatedDate DATETIME , DataBaseName  NVARCHAR(max) )
GO 
INSERT INTO Znode_Multifront_90..Znode_TempDBTable (Id,CreatedDate,DataBaseName )
SELECT 1 , GETDATE(),'Znode_Multifront_90'
GO 
SET NOEXEC OFF;
