//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Libraries.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Api_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Api_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Znode.Libraries.Resources.Api_Resources.Api_Resources", typeof(Api_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code cannot be empty..
        /// </summary>
        public static string AccountCodeCanNotBeEmpty {
            get {
                return ResourceManager.GetString("AccountCodeCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code is invalid.
        /// </summary>
        public static string AccountCodeIsInValidMessage {
            get {
                return ResourceManager.GetString("AccountCodeIsInValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code can not exceed 100 characters..
        /// </summary>
        public static string AccountCodeMaxLength {
            get {
                return ResourceManager.GetString("AccountCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to activate your license.&lt;br&gt;
        ///                If you are activating a Free Trial then proceed with the activation. You will have the option of creating an activation without using a license key.
        ///                &lt;br /&gt;
        ///                If you are using a purchased license, then you should be aware that this activation can only be used on one CPU..
        /// </summary>
        public static string ActivatelicenseText {
            get {
                return ResourceManager.GetString("ActivatelicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your License.
        /// </summary>
        public static string ActivateyourLicense {
            get {
                return ResourceManager.GetString("ActivateyourLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric characters are allowed; no special characters..
        /// </summary>
        public static string AlphaNumericOnly {
            get {
                return ResourceManager.GetString("AlphaNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric characters are allowed..
        /// </summary>
        public static string AlphanumericOnlyWithNoSpaces {
            get {
                return ResourceManager.GetString("AlphanumericOnlyWithNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Znode API seems to be unavailable or broken. Ask your system Administrator to directly check the Znode API for more details..
        /// </summary>
        public static string ApiNotAvailableMessage {
            get {
                return ResourceManager.GetString("ApiNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znode Web API.
        /// </summary>
        public static string APITitle {
            get {
                return ResourceManager.GetString("APITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Ids {0} already exists &amp; Shipping Ids {1} Associated Successfully..
        /// </summary>
        public static string AssociateShippingId {
            get {
                return ResourceManager.GetString("AssociateShippingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Shipping Id cannot be Null or Empty and Value must be Integer only..
        /// </summary>
        public static string AssociateShippingIdNotNullOrEmpty {
            get {
                return ResourceManager.GetString("AssociateShippingIdNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group cannot be associated since the attribute from the group is already associated.
        /// </summary>
        public static string AttributeAlreadyAssociated {
            get {
                return ResourceManager.GetString("AttributeAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Code can not exceed 100 characters..
        /// </summary>
        public static string AttributeCodeLength {
            get {
                return ResourceManager.GetString("AttributeCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute code with same value is already exists.
        /// </summary>
        public static string AttributeCodeValidation {
            get {
                return ResourceManager.GetString("AttributeCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Family Code.
        /// </summary>
        public static string AttributeFamilyCode {
            get {
                return ResourceManager.GetString("AttributeFamilyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Parameters.
        /// </summary>
        public static string BodyParameters {
            get {
                return ResourceManager.GetString("BodyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Code is invalid..
        /// </summary>
        public static string CatalogCodeIsInValidMessages {
            get {
                return ResourceManager.GetString("CatalogCodeIsInValidMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Code can not exceed 100 characters..
        /// </summary>
        public static string CatalogCodeMaxLength {
            get {
                return ResourceManager.GetString("CatalogCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use only alphabets and numbers..
        /// </summary>
        public static string ContainerKeyError {
            get {
                return ResourceManager.GetString("ContainerKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Key can not exceed 100 characters..
        /// </summary>
        public static string ContainerKeyLimit {
            get {
                return ResourceManager.GetString("ContainerKeyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Name can not exceed 100 characters..
        /// </summary>
        public static string ContainerNameLimit {
            get {
                return ResourceManager.GetString("ContainerNameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants created for non - published Content Containers cannot be published.Please publish the Content Container first..
        /// </summary>
        public static string ContainerPublishCheckForVariantPublish {
            get {
                return ResourceManager.GetString("ContainerPublishCheckForVariantPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is required..
        /// </summary>
        public static string ContentRequiredMessage {
            get {
                return ResourceManager.GetString("ContentRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2015 Znode, LLC..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon you are trying to apply cannot be clubbed with the already applied coupon..
        /// </summary>
        public static string CouponMessage {
            get {
                return ResourceManager.GetString("CouponMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current date or Future date .
        /// </summary>
        public static string CurrentDateMessage {
            get {
                return ResourceManager.GetString("CurrentDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default publish state can not be disabled..
        /// </summary>
        public static string DefaultPublishStateDisableErrorMessage {
            get {
                return ResourceManager.GetString("DefaultPublishStateDisableErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully..
        /// </summary>
        public static string DeleteAccountSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteAccountSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog deleted successfully..
        /// </summary>
        public static string DeleteCatalogSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteCatalogSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details not found..
        /// </summary>
        public static string DetailsNotFound {
            get {
                return ResourceManager.GetString("DetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Template Name is required..
        /// </summary>
        public static string EmailTemplateNameRequiredMessage {
            get {
                return ResourceManager.GetString("EmailTemplateNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter weighting..
        /// </summary>
        public static string EnterWeighting {
            get {
                return ResourceManager.GetString("EnterWeighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish failed due to an underlying entity model failure..
        /// </summary>
        public static string EntityExceptionMessageDuringPublish {
            get {
                return ResourceManager.GetString("EntityExceptionMessageDuringPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish could not be performed for the requested {0} since it does not exist..
        /// </summary>
        public static string EntityNotFoundMessageDuringPublish {
            get {
                return ResourceManager.GetString("EntityNotFoundMessageDuringPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code is required..
        /// </summary>
        public static string ErrorAccountCodeRequired {
            get {
                return ResourceManager.GetString("ErrorAccountCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatax connector error:.
        /// </summary>
        public static string ErrorAvataxConnection {
            get {
                return ResourceManager.GetString("ErrorAvataxConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing address id is required..
        /// </summary>
        public static string ErrorBillingAddressIdRequired {
            get {
                return ResourceManager.GetString("ErrorBillingAddressIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Code is required..
        /// </summary>
        public static string ErrorCatalogCodeRequired {
            get {
                return ResourceManager.GetString("ErrorCatalogCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete some Catalog as it is associated to a Store..
        /// </summary>
        public static string ErrorCatalogDelete {
            get {
                return ResourceManager.GetString("ErrorCatalogDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that the account, license, and URL settings have been provided in the configuration file..
        /// </summary>
        public static string ErrorCheckSettingsInConfigurationFile {
            get {
                return ResourceManager.GetString("ErrorCheckSettingsInConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert CMS Widget Slider Banner Configuration..
        /// </summary>
        public static string ErrorCMSWidgetContainerConfigurationInsert {
            get {
                return ResourceManager.GetString("ErrorCMSWidgetContainerConfigurationInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update CMS Widget Slider Banner Configuration..
        /// </summary>
        public static string ErrorCMSWidgetContainerConfigurationUpdate {
            get {
                return ResourceManager.GetString("ErrorCMSWidgetContainerConfigurationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Variant already exists..
        /// </summary>
        public static string ErrorContainerVariantAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorContainerVariantAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Container Id is Required.
        /// </summary>
        public static string ErrorContentContainerId {
            get {
                return ResourceManager.GetString("ErrorContentContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Container Key is Required.
        /// </summary>
        public static string ErrorContentContainerKey {
            get {
                return ResourceManager.GetString("ErrorContentContainerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Container Variant Id is required..
        /// </summary>
        public static string ErrorContentContainerVariantId {
            get {
                return ResourceManager.GetString("ErrorContentContainerVariantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain selections for this Quote request are either not available or are changed. Please contact the customer service to convert this quote to an order..
        /// </summary>
        public static string ErrorConvertQuoteToOrder {
            get {
                return ResourceManager.GetString("ErrorConvertQuoteToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer payment id or customer profile id is required..
        /// </summary>
        public static string ErrorCustomerPaymentIdRequired {
            get {
                return ResourceManager.GetString("ErrorCustomerPaymentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Variant cannot be deactivated..
        /// </summary>
        public static string ErrorDefaultVariantDeactivateMessage {
            get {
                return ResourceManager.GetString("ErrorDefaultVariantDeactivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default variant cannot be deleted..
        /// </summary>
        public static string ErrorDeleteDefaultContainerVariant {
            get {
                return ResourceManager.GetString("ErrorDeleteDefaultContainerVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total discount cannot exceed the SubTotal value..
        /// </summary>
        public static string ErrorDiscountExceeded {
            get {
                return ResourceManager.GetString("ErrorDiscountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string ErrorEmailAddress {
            get {
                return ResourceManager.GetString("ErrorEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate variant(s)..
        /// </summary>
        public static string ErrorFailedToActivateVariant {
            get {
                return ResourceManager.GetString("ErrorFailedToActivateVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deactivate variant(s)..
        /// </summary>
        public static string ErrorFailedToDeactivateVariant {
            get {
                return ResourceManager.GetString("ErrorFailedToDeactivateVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAllowedTerritories field is required..
        /// </summary>
        public static string ErrorIsAllowedTerritoriesRequired {
            get {
                return ResourceManager.GetString("ErrorIsAllowedTerritoriesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select if the Content Widget is Global.
        /// </summary>
        public static string ErrorIsGlobalContentWidget {
            get {
                return ResourceManager.GetString("ErrorIsGlobalContentWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username of a Guest User cannot be updated.
        /// </summary>
        public static string ErrorIsGuestUser {
            get {
                return ResourceManager.GetString("ErrorIsGuestUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not exceed {1} characters..
        /// </summary>
        public static string Errorlength {
            get {
                return ResourceManager.GetString("Errorlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CMSMappingId..
        /// </summary>
        public static string ErrorMessageForCMSMappingId {
            get {
                return ResourceManager.GetString("ErrorMessageForCMSMappingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WidgetsKey..
        /// </summary>
        public static string ErrorMessageForWidgetsKey {
            get {
                return ResourceManager.GetString("ErrorMessageForWidgetsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CMSMappingId or WidgetsKey..
        /// </summary>
        public static string ErrorMessageForWidgetsKeyAndCMSMappingId {
            get {
                return ResourceManager.GetString("ErrorMessageForWidgetsKeyAndCMSMappingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not exceed {1} characters..
        /// </summary>
        public static string ErrorMessageMaxLength {
            get {
                return ResourceManager.GetString("ErrorMessageMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name length can not exceed 200 characters..
        /// </summary>
        public static string ErrorMessageMaxLengthActionName {
            get {
                return ResourceManager.GetString("ErrorMessageMaxLengthActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Name length can not exceed 200 characters..
        /// </summary>
        public static string ErrorMessageMaxLengthControllerName {
            get {
                return ResourceManager.GetString("ErrorMessageMaxLengthControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name length can not exceed 100 characters..
        /// </summary>
        public static string ErrorMessageMaxLengthMenuName {
            get {
                return ResourceManager.GetString("ErrorMessageMaxLengthMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name length can not exceed 100 characters..
        /// </summary>
        public static string ErrorMessageMaxLengthRoleName {
            get {
                return ResourceManager.GetString("ErrorMessageMaxLengthRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model cannot be null..
        /// </summary>
        public static string ErrorModelNull {
            get {
                return ResourceManager.GetString("ErrorModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmsOrderDetailsId field is required..
        /// </summary>
        public static string ErrorOrderDetailsIdRequired {
            get {
                return ResourceManager.GetString("ErrorOrderDetailsIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderHistory field is required..
        /// </summary>
        public static string ErrorOrderHistoryRequired {
            get {
                return ResourceManager.GetString("ErrorOrderHistoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmsOrderId field is required..
        /// </summary>
        public static string ErrorOrderIdRequired {
            get {
                return ResourceManager.GetString("ErrorOrderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderLineItemHistory field is required..
        /// </summary>
        public static string ErrorOrderLineItemHistoryRequired {
            get {
                return ResourceManager.GetString("ErrorOrderLineItemHistoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderLineItems field is required..
        /// </summary>
        public static string ErrorOrderLineItemsRequired {
            get {
                return ResourceManager.GetString("ErrorOrderLineItemsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Payment Data model cannot be null..
        /// </summary>
        public static string ErrorOrderPaymentModelNull {
            get {
                return ResourceManager.GetString("ErrorOrderPaymentModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmsOrderStateId field is required..
        /// </summary>
        public static string ErrorOrderStateIdRequired {
            get {
                return ResourceManager.GetString("ErrorOrderStateIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderState field is required..
        /// </summary>
        public static string ErrorOrderStateRequired {
            get {
                return ResourceManager.GetString("ErrorOrderStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverDueAmount field is required..
        /// </summary>
        public static string ErrorOverDueAmountRequired {
            get {
                return ResourceManager.GetString("ErrorOverDueAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment setting id is required..
        /// </summary>
        public static string ErrorPaymentSettingIdRequired {
            get {
                return ResourceManager.GetString("ErrorPaymentSettingIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either ProfileId or PortalId..
        /// </summary>
        public static string ErrorPortalIdProfileId {
            get {
                return ResourceManager.GetString("ErrorPortalIdProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal id is required..
        /// </summary>
        public static string ErrorPortalIdRequired {
            get {
                return ResourceManager.GetString("ErrorPortalIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected payment method is already associated with the portal, please associate a different payment method.
        /// </summary>
        public static string ErrorPortalPaymentAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorPortalPaymentAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected payment method is already associated with profile, please associate a different payment method.
        /// </summary>
        public static string ErrorProfilePaymentAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorProfilePaymentAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create quote..
        /// </summary>
        public static string ErrorQuoteCreate {
            get {
                return ResourceManager.GetString("ErrorQuoteCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Id should be greater than zero..
        /// </summary>
        public static string ErrorQuoteIdGreaterThanZero {
            get {
                return ResourceManager.GetString("ErrorQuoteIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote id is required..
        /// </summary>
        public static string ErrorQuoteIdRequired {
            get {
                return ResourceManager.GetString("ErrorQuoteIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the Quote Line item..
        /// </summary>
        public static string ErrorQuoteLineItemDelete {
            get {
                return ResourceManager.GetString("ErrorQuoteLineItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote total is required..
        /// </summary>
        public static string ErrorQuoteTotalRequired {
            get {
                return ResourceManager.GetString("ErrorQuoteTotalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale Id is required..
        /// </summary>
        public static string ErrorRequiredLocaleId {
            get {
                return ResourceManager.GetString("ErrorRequiredLocaleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Id is required..
        /// </summary>
        public static string ErrorRequiredProfileId {
            get {
                return ResourceManager.GetString("ErrorRequiredProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnItemList field is required..
        /// </summary>
        public static string ErrorReturnItemListRequired {
            get {
                return ResourceManager.GetString("ErrorReturnItemListRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping address id is required..
        /// </summary>
        public static string ErrorShippingAddressIdRequired {
            get {
                return ResourceManager.GetString("ErrorShippingAddressIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingCost field is required..
        /// </summary>
        public static string ErrorShippingCostRequired {
            get {
                return ResourceManager.GetString("ErrorShippingCostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingDifference field is required..
        /// </summary>
        public static string ErrorShippingDifferenceRequired {
            get {
                return ResourceManager.GetString("ErrorShippingDifferenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping type id is required..
        /// </summary>
        public static string ErrorShippingIdRequired {
            get {
                return ResourceManager.GetString("ErrorShippingIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get shipping options with rates..
        /// </summary>
        public static string ErrorShippingOptionWithRatesGet {
            get {
                return ResourceManager.GetString("ErrorShippingOptionWithRatesGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShoppingCartItemsCount field is required..
        /// </summary>
        public static string ErrorShoppingCartItemsCountRequired {
            get {
                return ResourceManager.GetString("ErrorShoppingCartItemsCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShoppingCartOverDueAmount field is required..
        /// </summary>
        public static string ErrorShoppingCartOverDueAmountRequired {
            get {
                return ResourceManager.GetString("ErrorShoppingCartOverDueAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total field is required..
        /// </summary>
        public static string ErrorTotalRequired {
            get {
                return ResourceManager.GetString("ErrorTotalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id is required..
        /// </summary>
        public static string ErrorUserIdRequired {
            get {
                return ResourceManager.GetString("ErrorUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword property value of searchrequest model can&apos;t be null.
        /// </summary>
        public static string ExceptionMessageSearchKeyword {
            get {
                return ResourceManager.GetString("ExceptionMessageSearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search request model can&apos;t be null.
        /// </summary>
        public static string ExceptionMessageSearchModelNull {
            get {
                return ResourceManager.GetString("ExceptionMessageSearchModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try once the export process is completed..
        /// </summary>
        public static string ExportDownloadErrorMessage {
            get {
                return ResourceManager.GetString("ExportDownloadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string ExportErrorMessage {
            get {
                return ResourceManager.GetString("ExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Submission export has been initiated. Click here or redirect to the Exports screen to view more details.
        /// </summary>
        public static string ExportSuccessMessage {
            get {
                return ResourceManager.GetString("ExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Associate Account Profile to User Profile..
        /// </summary>
        public static string FailedAssociateAccountProfileToUserProfile {
            get {
                return ResourceManager.GetString("FailedAssociateAccountProfileToUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish failed..
        /// </summary>
        public static string GenericExceptionMessageDuringPublish {
            get {
                return ResourceManager.GetString("GenericExceptionMessageDuringPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid GST Tax (ex: 123.45)..
        /// </summary>
        public static string GSTTaxErrorMessage {
            get {
                return ResourceManager.GetString("GSTTaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight with same code already exists.
        /// </summary>
        public static string HighlightAlreadyExists {
            get {
                return ResourceManager.GetString("HighlightAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid HST Tax (ex: 123.45)..
        /// </summary>
        public static string HSTTaxErrorMessage {
            get {
                return ResourceManager.GetString("HSTTaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page cannot be displayed. Make sure you are authorized to view this page..
        /// </summary>
        public static string HttpCode_401_AccessDeniedMsg {
            get {
                return ResourceManager.GetString("HttpCode_401_AccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contact email..
        /// </summary>
        public static string InvalidContactEmail {
            get {
                return ResourceManager.GetString("InvalidContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Country Code..
        /// </summary>
        public static string InvalidCountryCode {
            get {
                return ResourceManager.GetString("InvalidCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Coupon Code.
        /// </summary>
        public static string InvalidCouponCode {
            get {
                return ResourceManager.GetString("InvalidCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed parent and the child product information doesn&apos;t belong to the same product.
        /// </summary>
        public static string InvalidDataForConfigurableProduct {
            get {
                return ResourceManager.GetString("InvalidDataForConfigurableProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a whole number..
        /// </summary>
        public static string InvalidDisplayOrder {
            get {
                return ResourceManager.GetString("InvalidDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This domain has not been configured to work with Znode..
        /// </summary>
        public static string InvalidDomainConfigurationMessage {
            get {
                return ResourceManager.GetString("InvalidDomainConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if the Elastic Search Service has been started on the host server and it is correctly configured to work with the Znode API..
        /// </summary>
        public static string InvalidElasticSearchConfigurationMessage {
            get {
                return ResourceManager.GetString("InvalidElasticSearchConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish cannot be performed since the supplied data is invalid..
        /// </summary>
        public static string InvalidEntityMessageDuringPublish {
            get {
                return ResourceManager.GetString("InvalidEntityMessageDuringPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid handling charge value..
        /// </summary>
        public static string InvalidHandlingChargeValue {
            get {
                return ResourceManager.GetString("InvalidHandlingChargeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid notification email..
        /// </summary>
        public static string InvalidNotificationEmailId {
            get {
                return ResourceManager.GetString("InvalidNotificationEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid portal Id.
        /// </summary>
        public static string InvalidPortalId {
            get {
                return ResourceManager.GetString("InvalidPortalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected quantity should be between {0} to {1}..
        /// </summary>
        public static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range of handing charge value ..
        /// </summary>
        public static string InvalidRange {
            get {
                return ResourceManager.GetString("InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range of Display Order..
        /// </summary>
        public static string InvalidShippingDisplayOrder {
            get {
                return ResourceManager.GetString("InvalidShippingDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if the SQL server has been correctly configured to work with the Znode API..
        /// </summary>
        public static string InvalidSqlConfigurationMessage {
            get {
                return ResourceManager.GetString("InvalidSqlConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid weighting value..
        /// </summary>
        public static string InvalidWeightingValue {
            get {
                return ResourceManager.GetString("InvalidWeightingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is verified.
        /// </summary>
        public static string IsVerifiedUser {
            get {
                return ResourceManager.GetString("IsVerifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string LabelActionName {
            get {
                return ResourceManager.GetString("LabelActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string LabelContentHtml {
            get {
                return ResourceManager.GetString("LabelContentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Name.
        /// </summary>
        public static string LabelControllerName {
            get {
                return ResourceManager.GetString("LabelControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Name.
        /// </summary>
        public static string LabelEmailTemplateName {
            get {
                return ResourceManager.GetString("LabelEmailTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Hands Date.
        /// </summary>
        public static string LabelInHandDate {
            get {
                return ResourceManager.GetString("LabelInHandDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string LabelIsActive {
            get {
                return ResourceManager.GetString("LabelIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parent Menu.
        /// </summary>
        public static string LabelIsParentMenu {
            get {
                return ResourceManager.GetString("LabelIsParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string LabelMenuName {
            get {
                return ResourceManager.GetString("LabelMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number.
        /// </summary>
        public static string LabelSequenceNumber {
            get {
                return ResourceManager.GetString("LabelSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Constraints.
        /// </summary>
        public static string LabelShippingConstraintsCode {
            get {
                return ResourceManager.GetString("LabelShippingConstraintsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Name.
        /// </summary>
        public static string LabelURLName {
            get {
                return ResourceManager.GetString("LabelURLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I wish to activate my license for this CPU. I also understand that once activated, my key can only be used on this CPU..
        /// </summary>
        public static string LicenceConfirmationMessage {
            get {
                return ResourceManager.GetString("LicenceConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum discount limit reached on the line item Total or the Subtotal..
        /// </summary>
        public static string MessageMaximumApplicableDiscount {
            get {
                return ResourceManager.GetString("MessageMaximumApplicableDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only a numeric value..
        /// </summary>
        public static string MessageNumericValueAllowed {
            get {
                return ResourceManager.GetString("MessageNumericValueAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence number can not exceed 15 characters..
        /// </summary>
        public static string MessageSequenceNumberLength {
            get {
                return ResourceManager.GetString("MessageSequenceNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model can not be null..
        /// </summary>
        public static string ModelNotNull {
            get {
                return ResourceManager.GetString("ModelNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum discount limit reached on the line item Total or the Subtotal.
        /// </summary>
        public static string NoFurtherCouponMessage {
            get {
                return ResourceManager.GetString("NoFurtherCouponMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum discount limit reached for Shipping..
        /// </summary>
        public static string NoFurtherShippingCouponMessage {
            get {
                return ResourceManager.GetString("NoFurtherShippingCouponMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Notes can not exceed 500 characters..
        /// </summary>
        public static string OrderNotesLengthErrorMessage {
            get {
                return ResourceManager.GetString("OrderNotesLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Attribute Code..
        /// </summary>
        public static string PleaseEnterAttributeCode {
            get {
                return ResourceManager.GetString("PleaseEnterAttributeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Display Order..
        /// </summary>
        public static string PleaseEnterDisplayOrder {
            get {
                return ResourceManager.GetString("PleaseEnterDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Handling Charges..
        /// </summary>
        public static string PleaseEnterHandlingCharges {
            get {
                return ResourceManager.GetString("PleaseEnterHandlingCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Name is required..
        /// </summary>
        public static string PleaseEnterPaymentName {
            get {
                return ResourceManager.GetString("PleaseEnterPaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Profile Name..
        /// </summary>
        public static string PleaseEnterProfileName {
            get {
                return ResourceManager.GetString("PleaseEnterProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Name is required. .
        /// </summary>
        public static string PleaseEnterShippingName {
            get {
                return ResourceManager.GetString("PleaseEnterShippingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Supplier Name..
        /// </summary>
        public static string PleaseEnterSupplierName {
            get {
                return ResourceManager.GetString("PleaseEnterSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a profile..
        /// </summary>
        public static string PleaseSelectProfile {
            get {
                return ResourceManager.GetString("PleaseSelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid Shipping Type..
        /// </summary>
        public static string PleaseSelectShippingType {
            get {
                return ResourceManager.GetString("PleaseSelectShippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select tax class..
        /// </summary>
        public static string PleaseSelectTaxClass {
            get {
                return ResourceManager.GetString("PleaseSelectTaxClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit the webstore to see the pricing.
        /// </summary>
        public static string PricingForLoggedInUsersMessage {
            get {
                return ResourceManager.GetString("PricingForLoggedInUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid PST Tax (ex: 123.45)..
        /// </summary>
        public static string PSTTaxErrorMessage {
            get {
                return ResourceManager.GetString("PSTTaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote number can not be empty..
        /// </summary>
        public static string QuoteNumberCanNotBeEmpty {
            get {
                return ResourceManager.GetString("QuoteNumberCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote number is invalid.
        /// </summary>
        public static string QuoteNumberIsInValidMessage {
            get {
                return ResourceManager.GetString("QuoteNumberIsInValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 0 and 100..
        /// </summary>
        public static string RangeBetween0to100 {
            get {
                return ResourceManager.GetString("RangeBetween0to100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than 0..
        /// </summary>
        public static string RangeGreaterThan0 {
            get {
                return ResourceManager.GetString("RangeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agreed to the software license agreement (EULA) above.
        /// </summary>
        public static string ReadAndAgreed {
            get {
                return ResourceManager.GetString("ReadAndAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Information.
        /// </summary>
        public static string RequestInformation {
            get {
                return ResourceManager.GetString("RequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 is required..
        /// </summary>
        public static string RequiredAddress1 {
            get {
                return ResourceManager.GetString("RequiredAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name is required..
        /// </summary>
        public static string RequiredClassName {
            get {
                return ResourceManager.GetString("RequiredClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Code is Required.
        /// </summary>
        public static string RequiredContainerTemplateCode {
            get {
                return ResourceManager.GetString("RequiredContainerTemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Container name is required..
        /// </summary>
        public static string RequiredContentContainerName {
            get {
                return ResourceManager.GetString("RequiredContentContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string RequiredDescription {
            get {
                return ResourceManager.GetString("RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order is required..
        /// </summary>
        public static string RequiredDisplayOrder {
            get {
                return ResourceManager.GetString("RequiredDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is required..
        /// </summary>
        public static string RequiredEmailID {
            get {
                return ResourceManager.GetString("RequiredEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Family Code is required..
        /// </summary>
        public static string RequiredFamilyCode {
            get {
                return ResourceManager.GetString("RequiredFamilyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Is Required..
        /// </summary>
        public static string RequiredFileNameErrorMessage {
            get {
                return ResourceManager.GetString("RequiredFileNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Action Name..
        /// </summary>
        public static string RequiredMessageActionName {
            get {
                return ResourceManager.GetString("RequiredMessageActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Controller Name..
        /// </summary>
        public static string RequiredMessageControllerName {
            get {
                return ResourceManager.GetString("RequiredMessageControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Menu Name..
        /// </summary>
        public static string RequiredMessageMenuName {
            get {
                return ResourceManager.GetString("RequiredMessageMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Menu Sequence Number..
        /// </summary>
        public static string RequiredMessageMenuSequenceNumber {
            get {
                return ResourceManager.GetString("RequiredMessageMenuSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Role Name..
        /// </summary>
        public static string RequiredMessageRoleName {
            get {
                return ResourceManager.GetString("RequiredMessageRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Name is required..
        /// </summary>
        public static string RequiredSchedulerName {
            get {
                return ResourceManager.GetString("RequiredSchedulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required..
        /// </summary>
        public static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required..
        /// </summary>
        public static string RequiredState {
            get {
                return ResourceManager.GetString("RequiredState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Point Name is required..
        /// </summary>
        public static string RequiredTouchPointName {
            get {
                return ResourceManager.GetString("RequiredTouchPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Description.
        /// </summary>
        public static string ResourceDescription {
            get {
                return ResourceManager.GetString("ResourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Formats.
        /// </summary>
        public static string ResponseFormats {
            get {
                return ResourceManager.GetString("ResponseFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Information.
        /// </summary>
        public static string ResponseInformation {
            get {
                return ResourceManager.GetString("ResponseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid Sales Tax (ex: 123.45)..
        /// </summary>
        public static string SalesTaxErrorMessage {
            get {
                return ResourceManager.GetString("SalesTaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Id Already Exist..
        /// </summary>
        public static string ShippingIdExist {
            get {
                return ResourceManager.GetString("ShippingIdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU is required..
        /// </summary>
        public static string SKURequiredMessage {
            get {
                return ResourceManager.GetString("SKURequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish failed due to an underlying sql agent failure..
        /// </summary>
        public static string SQLExceptionMessageDuringPublish {
            get {
                return ResourceManager.GetString("SQLExceptionMessageDuringPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store associated with the {0} has not been published..
        /// </summary>
        public static string StoreAssociatedWithEntityNotPublished {
            get {
                return ResourceManager.GetString("StoreAssociatedWithEntityNotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required..
        /// </summary>
        public static string SubjectRequiredMessage {
            get {
                return ResourceManager.GetString("SubjectRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account profile has been Associated to User Profile Successfully..
        /// </summary>
        public static string SuccessAssociateAccountProfileToUserProfile {
            get {
                return ResourceManager.GetString("SuccessAssociateAccountProfileToUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection success!.
        /// </summary>
        public static string SuccessAvataxConnection {
            get {
                return ResourceManager.GetString("SuccessAvataxConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Widget Slider Banner Configuration inserted successfully..
        /// </summary>
        public static string SuccessCMSWidgetContainerConfigurationInsert {
            get {
                return ResourceManager.GetString("SuccessCMSWidgetContainerConfigurationInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Widget Slider Banner Configuration with Id {0} updated successfully.
        /// </summary>
        public static string SuccessCMSWidgetContainerConfigurationUpdate {
            get {
                return ResourceManager.GetString("SuccessCMSWidgetContainerConfigurationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Line Item deleted successfully..
        /// </summary>
        public static string SuccessQuoteLineItemDelete {
            get {
                return ResourceManager.GetString("SuccessQuoteLineItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username updated successfully.
        /// </summary>
        public static string SuccessUpdateUsername {
            get {
                return ResourceManager.GetString("SuccessUpdateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Code can not exceed 100 characters..
        /// </summary>
        public static string TemplateCodeLimit {
            get {
                return ResourceManager.GetString("TemplateCodeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name is Required.
        /// </summary>
        public static string TemplateNameRequired {
            get {
                return ResourceManager.GetString("TemplateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Url.
        /// </summary>
        public static string ValidationUrl {
            get {
                return ResourceManager.GetString("ValidationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Variant(s) is activated..
        /// </summary>
        public static string VariantActivatedSuccessMessage {
            get {
                return ResourceManager.GetString("VariantActivatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Variant(s) is deactivated..
        /// </summary>
        public static string VariantDeactivatedSuccessMessage {
            get {
                return ResourceManager.GetString("VariantDeactivatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid VAT Tax (ex: 123.45)..
        /// </summary>
        public static string VATTaxErrorMessage {
            get {
                return ResourceManager.GetString("VATTaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znode 9_0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher code cannot be empty..
        /// </summary>
        public static string VoucherCodeCanNotBeEmpty {
            get {
                return ResourceManager.GetString("VoucherCodeCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher code is invalid.
        /// </summary>
        public static string VoucherCodeIsInValidMessage {
            get {
                return ResourceManager.GetString("VoucherCodeIsInValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code can not exceed 5000 characters..
        /// </summary>
        public static string ZipCodeLengthErrorMessage {
            get {
                return ResourceManager.GetString("ZipCodeLengthErrorMessage", resourceCulture);
            }
        }
    }
}
